// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package server

import (
	"context"

	"SLGaming/back/services/user/internal/logic"
	"SLGaming/back/services/user/internal/svc"
	"SLGaming/back/services/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Register(ctx context.Context, in *user.RegisterRequest) (*user.RegisterResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Login(ctx context.Context, in *user.LoginRequest) (*user.LoginResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *user.GetUserRequest) (*user.GetUserResponse, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

func (s *UserServer) UpdateUser(ctx context.Context, in *user.UpdateUserRequest) (*user.UpdateUserResponse, error) {
	l := logic.NewUpdateUserLogic(ctx, s.svcCtx)
	return l.UpdateUser(in)
}

func (s *UserServer) LoginByCode(ctx context.Context, in *user.LoginByCodeRequest) (*user.LoginByCodeResponse, error) {
	l := logic.NewLoginByCodeLogic(ctx, s.svcCtx)
	return l.LoginByCode(in)
}

func (s *UserServer) ForgetPassword(ctx context.Context, in *user.ForgetPasswordRequest) (*user.ForgetPasswordResponse, error) {
	l := logic.NewForgetPasswordLogic(ctx, s.svcCtx)
	return l.ForgetPassword(in)
}

// 帅币钱包相关接口
func (s *UserServer) GetWallet(ctx context.Context, in *user.GetWalletRequest) (*user.GetWalletResponse, error) {
	l := logic.NewGetWalletLogic(ctx, s.svcCtx)
	return l.GetWallet(in)
}

func (s *UserServer) Recharge(ctx context.Context, in *user.RechargeRequest) (*user.RechargeResponse, error) {
	l := logic.NewRechargeLogic(ctx, s.svcCtx)
	return l.Recharge(in)
}

func (s *UserServer) Consume(ctx context.Context, in *user.ConsumeRequest) (*user.ConsumeResponse, error) {
	l := logic.NewConsumeLogic(ctx, s.svcCtx)
	return l.Consume(in)
}

// 陪玩信息相关接口
func (s *UserServer) GetCompanionProfile(ctx context.Context, in *user.GetCompanionProfileRequest) (*user.GetCompanionProfileResponse, error) {
	l := logic.NewGetCompanionProfileLogic(ctx, s.svcCtx)
	return l.GetCompanionProfile(in)
}

func (s *UserServer) UpdateCompanionProfile(ctx context.Context, in *user.UpdateCompanionProfileRequest) (*user.UpdateCompanionProfileResponse, error) {
	l := logic.NewUpdateCompanionProfileLogic(ctx, s.svcCtx)
	return l.UpdateCompanionProfile(in)
}

func (s *UserServer) GetCompanionList(ctx context.Context, in *user.GetCompanionListRequest) (*user.GetCompanionListResponse, error) {
	l := logic.NewGetCompanionListLogic(ctx, s.svcCtx)
	return l.GetCompanionList(in)
}
