// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package orderclient

import (
	"context"

	"SLGaming/back/services/order/order"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AcceptOrderRequest    = order.AcceptOrderRequest
	AcceptOrderResponse   = order.AcceptOrderResponse
	CancelOrderRequest    = order.CancelOrderRequest
	CancelOrderResponse   = order.CancelOrderResponse
	CompleteOrderRequest  = order.CompleteOrderRequest
	CompleteOrderResponse = order.CompleteOrderResponse
	CreateOrderRequest    = order.CreateOrderRequest
	CreateOrderResponse   = order.CreateOrderResponse
	GetOrderListRequest   = order.GetOrderListRequest
	GetOrderListResponse  = order.GetOrderListResponse
	GetOrderRequest       = order.GetOrderRequest
	GetOrderResponse      = order.GetOrderResponse
	OrderInfo             = order.OrderInfo
	RateOrderRequest      = order.RateOrderRequest
	RateOrderResponse     = order.RateOrderResponse
	StartOrderRequest     = order.StartOrderRequest
	StartOrderResponse    = order.StartOrderResponse

	Order interface {
		// 订单创建与流转
		CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
		AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error)
		StartOrder(ctx context.Context, in *StartOrderRequest, opts ...grpc.CallOption) (*StartOrderResponse, error)
		CompleteOrder(ctx context.Context, in *CompleteOrderRequest, opts ...grpc.CallOption) (*CompleteOrderResponse, error)
		CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
		RateOrder(ctx context.Context, in *RateOrderRequest, opts ...grpc.CallOption) (*RateOrderResponse, error)
		// 查询相关
		GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
		GetOrderList(ctx context.Context, in *GetOrderListRequest, opts ...grpc.CallOption) (*GetOrderListResponse, error)
	}

	defaultOrder struct {
		cli zrpc.Client
	}
)

func NewOrder(cli zrpc.Client) Order {
	return &defaultOrder{
		cli: cli,
	}
}

// 订单创建与流转
func (m *defaultOrder) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrder) AcceptOrder(ctx context.Context, in *AcceptOrderRequest, opts ...grpc.CallOption) (*AcceptOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.AcceptOrder(ctx, in, opts...)
}

func (m *defaultOrder) StartOrder(ctx context.Context, in *StartOrderRequest, opts ...grpc.CallOption) (*StartOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.StartOrder(ctx, in, opts...)
}

func (m *defaultOrder) CompleteOrder(ctx context.Context, in *CompleteOrderRequest, opts ...grpc.CallOption) (*CompleteOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CompleteOrder(ctx, in, opts...)
}

func (m *defaultOrder) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

func (m *defaultOrder) RateOrder(ctx context.Context, in *RateOrderRequest, opts ...grpc.CallOption) (*RateOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.RateOrder(ctx, in, opts...)
}

// 查询相关
func (m *defaultOrder) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultOrder) GetOrderList(ctx context.Context, in *GetOrderListRequest, opts ...grpc.CallOption) (*GetOrderListResponse, error) {
	client := order.NewOrderClient(m.cli.Conn())
	return client.GetOrderList(ctx, in, opts...)
}
