// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"SLGaming/back/services/order/internal/logic"
	"SLGaming/back/services/order/internal/svc"
	"SLGaming/back/services/order/order"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	order.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

// 订单创建与流转
func (s *OrderServer) CreateOrder(ctx context.Context, in *order.CreateOrderRequest) (*order.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderServer) AcceptOrder(ctx context.Context, in *order.AcceptOrderRequest) (*order.AcceptOrderResponse, error) {
	l := logic.NewAcceptOrderLogic(ctx, s.svcCtx)
	return l.AcceptOrder(in)
}

func (s *OrderServer) StartOrder(ctx context.Context, in *order.StartOrderRequest) (*order.StartOrderResponse, error) {
	l := logic.NewStartOrderLogic(ctx, s.svcCtx)
	return l.StartOrder(in)
}

func (s *OrderServer) CompleteOrder(ctx context.Context, in *order.CompleteOrderRequest) (*order.CompleteOrderResponse, error) {
	l := logic.NewCompleteOrderLogic(ctx, s.svcCtx)
	return l.CompleteOrder(in)
}

func (s *OrderServer) CancelOrder(ctx context.Context, in *order.CancelOrderRequest) (*order.CancelOrderResponse, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

func (s *OrderServer) RateOrder(ctx context.Context, in *order.RateOrderRequest) (*order.RateOrderResponse, error) {
	l := logic.NewRateOrderLogic(ctx, s.svcCtx)
	return l.RateOrder(in)
}

// 查询相关
func (s *OrderServer) GetOrder(ctx context.Context, in *order.GetOrderRequest) (*order.GetOrderResponse, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

func (s *OrderServer) GetOrderList(ctx context.Context, in *order.GetOrderListRequest) (*order.GetOrderListResponse, error) {
	l := logic.NewGetOrderListLogic(ctx, s.svcCtx)
	return l.GetOrderList(in)
}

// 获取指定陪玩的订单评价列表（仅返回已评价订单）
