// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type ForgetPasswordRequest struct {
	Phone    string `json:"phone"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type ForgetPasswordResponse struct {
	BaseResp
	Data LoginData `json:"data"`
}

type GetUserRequest struct {
	Id    uint64 `form:"id,optional"`
	Uid   uint64 `form:"uid,optional"`
	Phone string `form:"phone,optional"`
}

type GetUserResponse struct {
	BaseResp
	Data UserInfo `json:"data"`
}

type LoginByCodeRequest struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type LoginByCodeResponse struct {
	BaseResp
	Data LoginData `json:"data"`
}

type LoginData struct {
	AccessToken string `json:"accessToken"`
}

type LoginRequest struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResponse struct {
	BaseResp
	Data LoginData `json:"data"`
}

type RegisterData struct {
	AccessToken string `json:"accessToken"`
}

type RegisterRequest struct {
	Phone    string `json:"phone"`
	Code     string `json:"code"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
}

type RegisterResponse struct {
	BaseResp
	Data RegisterData `json:"data"`
}

type SendCodeData struct {
	Success bool `json:"success"`
}

type SendCodeRequest struct {
	Phone   string `json:"phone"`
	Purpose string `json:"purpose"`
}

type SendCodeResponse struct {
	BaseResp
	Data SendCodeData `json:"data"`
}

type UpdateUserRequest struct {
	Id       uint64 `json:"id"`
	Nickname string `json:"nickname,optional"`
	Password string `json:"password,optional"`
	Phone    string `json:"phone,optional"`
}

type UpdateUserResponse struct {
	BaseResp
	Data UserInfo `json:"data"`
}

type UserInfo struct {
	Id       uint64 `json:"id"`
	Uid      uint64 `json:"uid"`
	Nickname string `json:"nickname"`
	Phone    string `json:"phone"`
}
