// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AcceptOrderRequest struct {
	OrderId uint64 `json:"orderId"` // 订单ID
}

type AcceptOrderResponse struct {
	BaseResp
	Data OrderInfo `json:"data"`
}

type AlipayNotifyRequest struct {
	Payload map[string]string `json:"payload"` // 支付宝异步通知参数
}

type AlipayNotifyResponse struct {
	BaseResp
}

type ApplyCompanionRequest struct {
	GameSkill    string `json:"gameSkill"`    // 游戏技能（单个游戏名称）
	PricePerHour int64  `json:"pricePerHour"` // 每小时价格（帅币）
	Bio          string `json:"bio,optional"` // 个人简介
}

type ApplyCompanionResponse struct {
	BaseResp
	Data UserInfo `json:"data"`
}

type BaseResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type CancelOrderRequest struct {
	OrderId uint64 `json:"orderId"`         // 订单ID
	Reason  string `json:"reason,optional"` // 取消原因
}

type CancelOrderResponse struct {
	BaseResp
	Data OrderInfo `json:"data"`
}

type ChangePasswordRequest struct {
	OldPhone    string `json:"oldPhone"`
	OldCode     string `json:"oldCode"`
	NewPassword string `json:"newPassword"`
}

type ChangePasswordResponse struct {
	BaseResp
}

type ChangePhoneRequest struct {
	OldPhone string `json:"oldPhone"`
	OldCode  string `json:"oldCode"`
	NewPhone string `json:"newPhone"`
	NewCode  string `json:"newCode"`
}

type ChangePhoneResponse struct {
	BaseResp
}

type CompanionInfo struct {
	UserId       uint64  `json:"userId"`       // 用户ID
	GameSkill    string  `json:"gameSkill"`    // 游戏技能（单个游戏名称）
	PricePerHour int64   `json:"pricePerHour"` // 每小时价格（帅币）
	Status       int     `json:"status"`       // 状态：0=离线, 1=在线, 2=忙碌
	Rating       float64 `json:"rating"`       // 评分（0-5分）
	TotalOrders  int64   `json:"totalOrders"`  // 总接单数
	IsVerified   bool    `json:"isVerified"`   // 是否认证
	Nickname     string  `json:"nickname"`     // 昵称
	AvatarUrl    string  `json:"avatarUrl"`    // 头像URL
	Bio          string  `json:"bio"`          // 个人简介
}

type CompleteOrderRequest struct {
	OrderId uint64 `json:"orderId"` // 订单ID
}

type CompleteOrderResponse struct {
	BaseResp
	Data OrderInfo `json:"data"`
}

type CreateOrderRequest struct {
	CompanionId     uint64 `json:"companionId"`       // 陪玩ID
	GameName        string `json:"gameName"`          // 游戏名称
	GameMode        string `json:"gameMode,optional"` // 游戏模式/段位
	DurationMinutes int32  `json:"durationMinutes"`   // 服务时长（分钟）
}

type CreateOrderResponse struct {
	BaseResp
	Data OrderInfo `json:"data"`
}

type ForgetPasswordRequest struct {
	Phone    string `json:"phone"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

type ForgetPasswordResponse struct {
	BaseResp
	Data LoginData `json:"data"`
}

type GameSkill struct {
	Id          uint64 `json:"id"`          // 技能ID
	Name        string `json:"name"`        // 技能名称
	Description string `json:"description"` // 技能描述
}

type GetCompanionListData struct {
	Companions []CompanionInfo `json:"companions"` // 陪玩列表
	Total      int             `json:"total"`      // 总数
	Page       int             `json:"page"`       // 当前页码
	PageSize   int             `json:"pageSize"`   // 每页数量
}

type GetCompanionListRequest struct {
	GameSkill  string `form:"gameSkill,optional"`  // 游戏技能筛选（单个游戏名称）
	MinPrice   int    `form:"minPrice,optional"`   // 最低价格
	MaxPrice   int    `form:"maxPrice,optional"`   // 最高价格
	Status     int    `form:"status,optional"`     // 状态筛选：0=离线, 1=在线, 2=忙碌（默认1）
	IsVerified bool   `form:"isVerified,optional"` // 是否只返回认证陪玩
	Page       int    `form:"page,optional"`       // 页码（从1开始）
	PageSize   int    `form:"pageSize,optional"`   // 每页数量
}

type GetCompanionListResponse struct {
	BaseResp
	Data GetCompanionListData `json:"data"`
}

type GetCompanionProfileByIdRequest struct {
	UserId uint64 `form:"userId"` // 目标用户ID
}

type GetCompanionProfileResponse struct {
	BaseResp
	Data CompanionInfo `json:"data"`
}

type GetOrderListData struct {
	Orders   []OrderInfo `json:"orders"`
	Total    int32       `json:"total"`
	Page     int32       `json:"page"`
	PageSize int32       `json:"pageSize"`
}

type GetOrderListRequest struct {
	Role     string `form:"role,optional"`     // 角色：boss / companion（默认 boss）
	Status   int32  `form:"status,optional"`   // 状态筛选
	Page     int32  `form:"page,optional"`     // 页码
	PageSize int32  `form:"pageSize,optional"` // 每页数量
}

type GetOrderListResponse struct {
	BaseResp
	Data GetOrderListData `json:"data"`
}

type GetOrderRequest struct {
	Id      uint64 `form:"id,optional"`      // 订单ID
	OrderNo string `form:"orderNo,optional"` // 订单号
}

type GetOrderResponse struct {
	BaseResp
	Data OrderInfo `json:"data"`
}

type GetUserRequest struct {
	Id    uint64 `form:"id,optional"`
	Uid   uint64 `form:"uid,optional"`
	Phone string `form:"phone,optional"`
}

type GetUserResponse struct {
	BaseResp
	Data UserInfo `json:"data"`
}

type GetWalletResponse struct {
	BaseResp
	Data WalletInfo `json:"data"`
}

type ListGameSkillsResponse struct {
	BaseResp
	Data []GameSkill `json:"data"`
}

type LoginByCodeRequest struct {
	Phone string `json:"phone"`
	Code  string `json:"code"`
}

type LoginByCodeResponse struct {
	BaseResp
	Data LoginData `json:"data"`
}

type LoginData struct {
	AccessToken  string `json:"accessToken"`  // Access Token（短期，15分钟）
	RefreshToken string `json:"refreshToken"` // Refresh Token（长期，7天）
	ExpiresIn    int64  `json:"expiresIn"`    // Access Token 过期时间（秒）
}

type LoginRequest struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResponse struct {
	BaseResp
	Data LoginData `json:"data"`
}

type LogoutData struct {
	Success bool `json:"success"`
}

type LogoutRequest struct {
}

type LogoutResponse struct {
	BaseResp
	Data LogoutData `json:"data"`
}

type OrderInfo struct {
	Id           uint64  `json:"id"`           // 订单ID
	OrderNo      string  `json:"orderNo"`      // 订单号
	BossId       uint64  `json:"bossId"`       // 老板ID
	CompanionId  uint64  `json:"companionId"`  // 陪玩ID
	GameName     string  `json:"gameName"`     // 游戏名称
	GameMode     string  `json:"gameMode"`     // 游戏模式/段位
	Duration     int32   `json:"duration"`     // 时长（分钟）
	PricePerHour int64   `json:"pricePerHour"` // 每小时价格（帅币）
	TotalAmount  int64   `json:"totalAmount"`  // 订单总价（帅币）
	Status       int32   `json:"status"`       // 状态：1=CREATED,2=PAID,3=ACCEPTED,4=IN_SERVICE,5=COMPLETED,6=CANCELLED,7=RATED
	CreatedAt    int64   `json:"createdAt"`    // 创建时间
	PaidAt       int64   `json:"paidAt"`       // 支付时间
	AcceptedAt   int64   `json:"acceptedAt"`   // 接单时间
	StartAt      int64   `json:"startAt"`      // 开始服务时间
	CompletedAt  int64   `json:"completedAt"`  // 完成时间
	CancelledAt  int64   `json:"cancelledAt"`  // 取消时间
	Rating       float64 `json:"rating"`       // 评分
	Comment      string  `json:"comment"`      // 评价内容
	CancelReason string  `json:"cancelReason"` // 取消原因
}

type RateOrderRequest struct {
	OrderId uint64  `json:"orderId"`          // 订单ID
	Rating  float64 `json:"rating"`           // 评分（0-5）
	Comment string  `json:"comment,optional"` // 评价内容
}

type RateOrderResponse struct {
	BaseResp
	Data OrderInfo `json:"data"`
}

type RechargeCreateData struct {
	OrderNo   string `json:"orderNo"`   // 充值单号
	PayUrl    string `json:"payUrl"`    // 支付跳转URL（WAP/PC）
	PayForm   string `json:"payForm"`   // 支付表单（APP/PC场景可选）
	ExpiresIn int64  `json:"expiresIn"` // 订单有效期（秒）
}

type RechargeCreateRequest struct {
	Amount    int64  `json:"amount"`             // 充值金额（分/帅币）
	PayType   string `json:"payType"`            // 支付方式：alipay_wap / alipay_page / alipay_app
	ReturnUrl string `json:"returnUrl,optional"` // 同步回跳地址（可选）
}

type RechargeCreateResponse struct {
	BaseResp
	Data RechargeCreateData `json:"data"`
}

type RechargeQueryData struct {
	OrderNo string `json:"orderNo"`
	Status  int    `json:"status"` // 订单状态：0=待支付,1=成功,2=失败,3=关闭
	Amount  int64  `json:"amount"`
}

type RechargeQueryRequest struct {
	OrderNo string `form:"orderNo"` // 充值单号
}

type RechargeQueryResponse struct {
	BaseResp
	Data RechargeQueryData `json:"data"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

type RefreshTokenResponse struct {
	BaseResp
	Data LoginData `json:"data"`
}

type RegisterData struct {
	AccessToken  string `json:"accessToken"`  // Access Token（短期，15分钟）
	RefreshToken string `json:"refreshToken"` // Refresh Token（长期，7天）
	ExpiresIn    int64  `json:"expiresIn"`    // Access Token 过期时间（秒）
}

type RegisterRequest struct {
	Phone    string `json:"phone"`
	Code     string `json:"code"`
	Password string `json:"password"`
	Nickname string `json:"nickname,optional"`
	Role     int    `json:"role,optional"` // 用户角色：1=老板, 2=陪玩, 3=管理员（默认1）
}

type RegisterResponse struct {
	BaseResp
	Data RegisterData `json:"data"`
}

type SendCodeData struct {
	Success bool `json:"success"`
}

type SendCodeRequest struct {
	Phone   string `json:"phone"`
	Purpose string `json:"purpose"`
}

type SendCodeResponse struct {
	BaseResp
	Data SendCodeData `json:"data"`
}

type StartOrderRequest struct {
	OrderId uint64 `json:"orderId"` // 订单ID
}

type StartOrderResponse struct {
	BaseResp
	Data OrderInfo `json:"data"`
}

type UpdateCompanionProfileRequest struct {
	GameSkill    string `json:"gameSkill,optional"`    // 游戏技能（单个游戏名称）
	PricePerHour int64  `json:"pricePerHour,optional"` // 每小时价格（帅币）
	Status       int    `json:"status,optional"`       // 状态：0=离线, 1=在线, 2=忙碌
}

type UpdateCompanionProfileResponse struct {
	BaseResp
	Data CompanionInfo `json:"data"`
}

type UpdateCompanionStatusRequest struct {
	Status int `json:"status"` // 状态：0=离线, 1=在线, 2=忙碌
}

type UpdateCompanionStatusResponse struct {
	BaseResp
	Data CompanionInfo `json:"data"`
}

type UpdateUserRequest struct {
	Id        uint64 `json:"id"`
	Nickname  string `json:"nickname,optional"`
	Password  string `json:"password,optional"`
	Phone     string `json:"phone,optional"`
	Role      int    `json:"role,optional"`      // 用户角色
	AvatarUrl string `json:"avatarUrl,optional"` // 头像URL
	Bio       string `json:"bio,optional"`       // 个人简介
}

type UpdateUserResponse struct {
	BaseResp
	Data UserInfo `json:"data"`
}

type UploadAvatarData struct {
	AvatarUrl string `json:"avatarUrl"` // 头像URL
}

type UploadAvatarRequest struct {
	Avatar string `form:"avatar"` // 头像文件（multipart/form-data 文件字段）
}

type UploadAvatarResponse struct {
	BaseResp
	Data UploadAvatarData `json:"data"`
}

type UserInfo struct {
	Id            uint64 `json:"id"`
	Uid           uint64 `json:"uid"`
	Nickname      string `json:"nickname"`
	Phone         string `json:"phone"`
	Role          int    `json:"role"`          // 用户角色：1=老板, 2=陪玩, 3=管理员
	AvatarUrl     string `json:"avatarUrl"`     // 头像URL
	Bio           string `json:"bio"`           // 个人简介
	Balance       int64  `json:"balance"`       // 帅币可用余额
	FrozenBalance int64  `json:"frozenBalance"` // 冻结帅币余额（预留）
}

type WalletInfo struct {
	UserId        uint64 `json:"userId"`
	Balance       int64  `json:"balance"`
	FrozenBalance int64  `json:"frozenBalance"`
}
