// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: agent.proto

package agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Agent_RecommendCompanion_FullMethodName     = "/agent.Agent/RecommendCompanion"
	Agent_AddCompanionToVectorDB_FullMethodName = "/agent.Agent/AddCompanionToVectorDB"
	Agent_ModerateAvatar_FullMethodName         = "/agent.Agent/ModerateAvatar"
)

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 陪玩推荐 Agent 服务
type AgentClient interface {
	// 根据用户输入推荐陪玩
	RecommendCompanion(ctx context.Context, in *RecommendCompanionRequest, opts ...grpc.CallOption) (*RecommendCompanionResponse, error)
	// 添加陪玩信息到向量数据库
	AddCompanionToVectorDB(ctx context.Context, in *AddCompanionToVectorDBRequest, opts ...grpc.CallOption) (*AddCompanionToVectorDBResponse, error)
	// 头像多模态审核
	ModerateAvatar(ctx context.Context, in *ModerateAvatarRequest, opts ...grpc.CallOption) (*ModerateAvatarResponse, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) RecommendCompanion(ctx context.Context, in *RecommendCompanionRequest, opts ...grpc.CallOption) (*RecommendCompanionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendCompanionResponse)
	err := c.cc.Invoke(ctx, Agent_RecommendCompanion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AddCompanionToVectorDB(ctx context.Context, in *AddCompanionToVectorDBRequest, opts ...grpc.CallOption) (*AddCompanionToVectorDBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCompanionToVectorDBResponse)
	err := c.cc.Invoke(ctx, Agent_AddCompanionToVectorDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) ModerateAvatar(ctx context.Context, in *ModerateAvatarRequest, opts ...grpc.CallOption) (*ModerateAvatarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModerateAvatarResponse)
	err := c.cc.Invoke(ctx, Agent_ModerateAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility.
//
// 陪玩推荐 Agent 服务
type AgentServer interface {
	// 根据用户输入推荐陪玩
	RecommendCompanion(context.Context, *RecommendCompanionRequest) (*RecommendCompanionResponse, error)
	// 添加陪玩信息到向量数据库
	AddCompanionToVectorDB(context.Context, *AddCompanionToVectorDBRequest) (*AddCompanionToVectorDBResponse, error)
	// 头像多模态审核
	ModerateAvatar(context.Context, *ModerateAvatarRequest) (*ModerateAvatarResponse, error)
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServer struct{}

func (UnimplementedAgentServer) RecommendCompanion(context.Context, *RecommendCompanionRequest) (*RecommendCompanionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecommendCompanion not implemented")
}
func (UnimplementedAgentServer) AddCompanionToVectorDB(context.Context, *AddCompanionToVectorDBRequest) (*AddCompanionToVectorDBResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddCompanionToVectorDB not implemented")
}
func (UnimplementedAgentServer) ModerateAvatar(context.Context, *ModerateAvatarRequest) (*ModerateAvatarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModerateAvatar not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}
func (UnimplementedAgentServer) testEmbeddedByValue()               {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	// If the following call panics, it indicates UnimplementedAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_RecommendCompanion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendCompanionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).RecommendCompanion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_RecommendCompanion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).RecommendCompanion(ctx, req.(*RecommendCompanionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AddCompanionToVectorDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCompanionToVectorDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AddCompanionToVectorDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_AddCompanionToVectorDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AddCompanionToVectorDB(ctx, req.(*AddCompanionToVectorDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_ModerateAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModerateAvatarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).ModerateAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Agent_ModerateAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).ModerateAvatar(ctx, req.(*ModerateAvatarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecommendCompanion",
			Handler:    _Agent_RecommendCompanion_Handler,
		},
		{
			MethodName: "AddCompanionToVectorDB",
			Handler:    _Agent_AddCompanionToVectorDB_Handler,
		},
		{
			MethodName: "ModerateAvatar",
			Handler:    _Agent_ModerateAvatar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
