// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: agent.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 推荐陪玩请求
type RecommendCompanionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInput     string                 `protobuf:"bytes,1,opt,name=user_input,json=userInput,proto3" json:"user_input,omitempty"` // 用户输入内容（如："我想要一个王者荣耀的陪玩"）
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`         // 用户ID（可选，用于个性化推荐）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendCompanionRequest) Reset() {
	*x = RecommendCompanionRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendCompanionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendCompanionRequest) ProtoMessage() {}

func (x *RecommendCompanionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendCompanionRequest.ProtoReflect.Descriptor instead.
func (*RecommendCompanionRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RecommendCompanionRequest) GetUserInput() string {
	if x != nil {
		return x.UserInput
	}
	return ""
}

func (x *RecommendCompanionRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// 陪玩推荐结果
type CompanionRecommendation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 陪玩用户ID
	GameSkill     string                 `protobuf:"bytes,2,opt,name=game_skill,json=gameSkill,proto3" json:"game_skill,omitempty"`             // 游戏技能
	Gender        string                 `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`                                    // 性别
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`                                         // 年龄
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                          // 描述
	PricePerHour  int64                  `protobuf:"varint,6,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"` // 每小时价格
	Rating        float64                `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`                                  // 评分
	Similarity    float64                `protobuf:"fixed64,8,opt,name=similarity,proto3" json:"similarity,omitempty"`                          // 相似度分数（0-1）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanionRecommendation) Reset() {
	*x = CompanionRecommendation{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionRecommendation) ProtoMessage() {}

func (x *CompanionRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionRecommendation.ProtoReflect.Descriptor instead.
func (*CompanionRecommendation) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CompanionRecommendation) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompanionRecommendation) GetGameSkill() string {
	if x != nil {
		return x.GameSkill
	}
	return ""
}

func (x *CompanionRecommendation) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CompanionRecommendation) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CompanionRecommendation) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CompanionRecommendation) GetPricePerHour() int64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *CompanionRecommendation) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CompanionRecommendation) GetSimilarity() float64 {
	if x != nil {
		return x.Similarity
	}
	return 0
}

// 推荐陪玩响应
type RecommendCompanionResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Companions    []*CompanionRecommendation `protobuf:"bytes,1,rep,name=companions,proto3" json:"companions,omitempty"`   // 推荐的陪玩列表
	Explanation   string                     `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"` // 推荐理由说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendCompanionResponse) Reset() {
	*x = RecommendCompanionResponse{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendCompanionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendCompanionResponse) ProtoMessage() {}

func (x *RecommendCompanionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendCompanionResponse.ProtoReflect.Descriptor instead.
func (*RecommendCompanionResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendCompanionResponse) GetCompanions() []*CompanionRecommendation {
	if x != nil {
		return x.Companions
	}
	return nil
}

func (x *RecommendCompanionResponse) GetExplanation() string {
	if x != nil {
		return x.Explanation
	}
	return ""
}

// 添加陪玩信息到向量数据库请求
type AddCompanionToVectorDBRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 用户ID（必填）
	Gender        string                 `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`                                    // 性别：male/female/other
	Age           int32                  `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`                                         // 年龄
	GameSkill     string                 `protobuf:"bytes,4,opt,name=game_skill,json=gameSkill,proto3" json:"game_skill,omitempty"`             // 游戏技能（单个游戏名称）
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                          // 陪玩描述文本（用于向量化）
	PricePerHour  int64                  `protobuf:"varint,6,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"` // 每小时价格（帅币）
	Rating        float64                `protobuf:"fixed64,7,opt,name=rating,proto3" json:"rating,omitempty"`                                  // 评分（0-5分）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCompanionToVectorDBRequest) Reset() {
	*x = AddCompanionToVectorDBRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCompanionToVectorDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCompanionToVectorDBRequest) ProtoMessage() {}

func (x *AddCompanionToVectorDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCompanionToVectorDBRequest.ProtoReflect.Descriptor instead.
func (*AddCompanionToVectorDBRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AddCompanionToVectorDBRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddCompanionToVectorDBRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *AddCompanionToVectorDBRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *AddCompanionToVectorDBRequest) GetGameSkill() string {
	if x != nil {
		return x.GameSkill
	}
	return ""
}

func (x *AddCompanionToVectorDBRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AddCompanionToVectorDBRequest) GetPricePerHour() int64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *AddCompanionToVectorDBRequest) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

// 添加陪玩信息到向量数据库响应
type AddCompanionToVectorDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanionId   uint64                 `protobuf:"varint,1,opt,name=companion_id,json=companionId,proto3" json:"companion_id,omitempty"` // 陪玩ID（Milvus中的ID）
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`                            // 是否成功
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`                             // 提示信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddCompanionToVectorDBResponse) Reset() {
	*x = AddCompanionToVectorDBResponse{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddCompanionToVectorDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCompanionToVectorDBResponse) ProtoMessage() {}

func (x *AddCompanionToVectorDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCompanionToVectorDBResponse.ProtoReflect.Descriptor instead.
func (*AddCompanionToVectorDBResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AddCompanionToVectorDBResponse) GetCompanionId() uint64 {
	if x != nil {
		return x.CompanionId
	}
	return 0
}

func (x *AddCompanionToVectorDBResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddCompanionToVectorDBResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"S\n" +
	"\x19RecommendCompanionRequest\x12\x1d\n" +
	"\n" +
	"user_input\x18\x01 \x01(\tR\tuserInput\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\"\xfb\x01\n" +
	"\x17CompanionRecommendation\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"game_skill\x18\x02 \x01(\tR\tgameSkill\x12\x16\n" +
	"\x06gender\x18\x03 \x01(\tR\x06gender\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12$\n" +
	"\x0eprice_per_hour\x18\x06 \x01(\x03R\fpricePerHour\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\x12\x1e\n" +
	"\n" +
	"similarity\x18\b \x01(\x01R\n" +
	"similarity\"~\n" +
	"\x1aRecommendCompanionResponse\x12>\n" +
	"\n" +
	"companions\x18\x01 \x03(\v2\x1e.agent.CompanionRecommendationR\n" +
	"companions\x12 \n" +
	"\vexplanation\x18\x02 \x01(\tR\vexplanation\"\xe1\x01\n" +
	"\x1dAddCompanionToVectorDBRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\tR\x06gender\x12\x10\n" +
	"\x03age\x18\x03 \x01(\x05R\x03age\x12\x1d\n" +
	"\n" +
	"game_skill\x18\x04 \x01(\tR\tgameSkill\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12$\n" +
	"\x0eprice_per_hour\x18\x06 \x01(\x03R\fpricePerHour\x12\x16\n" +
	"\x06rating\x18\a \x01(\x01R\x06rating\"w\n" +
	"\x1eAddCompanionToVectorDBResponse\x12!\n" +
	"\fcompanion_id\x18\x01 \x01(\x04R\vcompanionId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage2\xc9\x01\n" +
	"\x05Agent\x12Y\n" +
	"\x12RecommendCompanion\x12 .agent.RecommendCompanionRequest\x1a!.agent.RecommendCompanionResponse\x12e\n" +
	"\x16AddCompanionToVectorDB\x12$.agent.AddCompanionToVectorDBRequest\x1a%.agent.AddCompanionToVectorDBResponseB\tZ\a./agentb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_agent_proto_goTypes = []any{
	(*RecommendCompanionRequest)(nil),      // 0: agent.RecommendCompanionRequest
	(*CompanionRecommendation)(nil),        // 1: agent.CompanionRecommendation
	(*RecommendCompanionResponse)(nil),     // 2: agent.RecommendCompanionResponse
	(*AddCompanionToVectorDBRequest)(nil),  // 3: agent.AddCompanionToVectorDBRequest
	(*AddCompanionToVectorDBResponse)(nil), // 4: agent.AddCompanionToVectorDBResponse
}
var file_agent_proto_depIdxs = []int32{
	1, // 0: agent.RecommendCompanionResponse.companions:type_name -> agent.CompanionRecommendation
	0, // 1: agent.Agent.RecommendCompanion:input_type -> agent.RecommendCompanionRequest
	3, // 2: agent.Agent.AddCompanionToVectorDB:input_type -> agent.AddCompanionToVectorDBRequest
	2, // 3: agent.Agent.RecommendCompanion:output_type -> agent.RecommendCompanionResponse
	4, // 4: agent.Agent.AddCompanionToVectorDB:output_type -> agent.AddCompanionToVectorDBResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
