// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: agent.proto

package server

import (
	"context"

	"SLGaming/back/services/agent/agent"
	"SLGaming/back/services/agent/internal/logic"
	"SLGaming/back/services/agent/internal/svc"
)

type AgentServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedAgentServer
}

func NewAgentServer(svcCtx *svc.ServiceContext) *AgentServer {
	return &AgentServer{
		svcCtx: svcCtx,
	}
}

// 健康检查
func (s *AgentServer) Ping(ctx context.Context, in *agent.PingRequest) (*agent.PingResponse, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

// 发送用户消息，返回 Agent 回复
func (s *AgentServer) SendMessage(ctx context.Context, in *agent.SendMessageRequest) (*agent.SendMessageResponse, error) {
	l := logic.NewSendMessageLogic(ctx, s.svcCtx)
	return l.SendMessage(in)
}

// 获取会话列表
func (s *AgentServer) GetSessionList(ctx context.Context, in *agent.GetSessionListRequest) (*agent.GetSessionListResponse, error) {
	l := logic.NewGetSessionListLogic(ctx, s.svcCtx)
	return l.GetSessionList(in)
}

// 获取会话消息历史
func (s *AgentServer) GetMessageHistory(ctx context.Context, in *agent.GetMessageHistoryRequest) (*agent.GetMessageHistoryResponse, error) {
	l := logic.NewGetMessageHistoryLogic(ctx, s.svcCtx)
	return l.GetMessageHistory(in)
}
