// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: agent.proto

package server

import (
	"context"
	"time"

	"SLGaming/back/services/agent/agent"
	"SLGaming/back/services/agent/internal/logic"
	"SLGaming/back/services/agent/internal/svc"

	"github.com/zeromicro/go-zero/core/logx"
)

type AgentServer struct {
	svcCtx *svc.ServiceContext
	agent.UnimplementedAgentServer
}

func NewAgentServer(svcCtx *svc.ServiceContext) *AgentServer {
	return &AgentServer{
		svcCtx: svcCtx,
	}
}

// 根据用户输入推荐陪玩
func (s *AgentServer) RecommendCompanion(ctx context.Context, in *agent.RecommendCompanionRequest) (*agent.RecommendCompanionResponse, error) {
	logger := logx.WithContext(ctx)
	start := time.Now()
	userID := in.GetUserId()
	userInput := in.GetUserInput()
	logger.Infof("rpc=RecommendCompanion start user_id=%d user_input_len=%d user_input=%.100s", userID, len(userInput), userInput)
	l := logic.NewRecommendCompanionLogic(ctx, s.svcCtx)
	resp, err := l.RecommendCompanion(in)
	companionCount := 0
	if resp != nil && resp.Companions != nil {
		companionCount = len(resp.Companions)
	}
	logger.Infof("rpc=RecommendCompanion done user_id=%d companion_count=%d err=%v duration=%s", userID, companionCount, err, time.Since(start))
	return resp, err
}

// 添加陪玩信息到向量数据库
func (s *AgentServer) AddCompanionToVectorDB(ctx context.Context, in *agent.AddCompanionToVectorDBRequest) (*agent.AddCompanionToVectorDBResponse, error) {
	logger := logx.WithContext(ctx)
	start := time.Now()
	userID := in.GetUserId()
	gameSkill := in.GetGameSkill()
	age := in.GetAge()
	logger.Infof("rpc=AddCompanionToVectorDB start user_id=%d game_skill=%s age=%d price_per_hour=%d", userID, gameSkill, age, in.GetPricePerHour())
	l := logic.NewAddCompanionToVectorDBLogic(ctx, s.svcCtx)
	resp, err := l.AddCompanionToVectorDB(in)
	success := false
	if resp != nil {
		success = resp.Success
	}
	logger.Infof("rpc=AddCompanionToVectorDB done user_id=%d success=%v err=%v duration=%s", userID, success, err, time.Since(start))
	return resp, err
}

// 头像多模态审核
func (s *AgentServer) ModerateAvatar(ctx context.Context, in *agent.ModerateAvatarRequest) (*agent.ModerateAvatarResponse, error) {
	logger := logx.WithContext(ctx)
	start := time.Now()
	userID := in.GetUserId()
	requestID := in.GetRequestId()
	logger.Infof("rpc=ModerateAvatar start user_id=%d request_id=%s image_url_len=%d image_base64_len=%d", userID, requestID, len(in.GetImageUrl()), len(in.GetImageBase64()))
	l := logic.NewModerateAvatarLogic(ctx, s.svcCtx)
	resp, err := l.ModerateAvatar(in)
	decision := "unknown"
	if resp != nil {
		decision = resp.Decision.String()
	}
	logger.Infof("rpc=ModerateAvatar done user_id=%d request_id=%s decision=%s err=%v duration=%s", userID, requestID, decision, err, time.Since(start))
	return resp, err
}
