// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Role          int32                  `protobuf:"varint,4,opt,name=role,proto3" json:"role,omitempty"` // 用户角色：1=老板, 2=陪玩, 3=管理员（默认1）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RegisterResponse) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginResponse) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetUserRequest) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *GetUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Role          int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`                                        // 用户角色：1=老板, 2=陪玩, 3=管理员
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`              // 头像URL
	Bio           string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`                                           // 个人简介
	Balance       int64                  `protobuf:"varint,8,opt,name=balance,proto3" json:"balance,omitempty"`                                  // 帅币可用余额
	FrozenBalance int64                  `protobuf:"varint,9,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"` // 冻结帅币余额（预留）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserInfo) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *UserInfo) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *UserInfo) GetFrozenBalance() int64 {
	if x != nil {
		return x.FrozenBalance
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type UpdateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 可选
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`                    // 可选
	Phone         string                 `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`                          // 可选
	Role          int32                  `protobuf:"varint,5,opt,name=role,proto3" json:"role,omitempty"`                           // 可选，用户角色
	AvatarUrl     string                 `protobuf:"bytes,6,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 可选，头像URL
	Bio           string                 `protobuf:"bytes,7,opt,name=bio,proto3" json:"bio,omitempty"`                              // 可选，个人简介
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserRequest) Reset() {
	*x = UpdateUserRequest{}
	mi := &file_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserRequest) ProtoMessage() {}

func (x *UpdateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateUserRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateUserRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UpdateUserRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateUserRequest) GetRole() int32 {
	if x != nil {
		return x.Role
	}
	return 0
}

func (x *UpdateUserRequest) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UpdateUserRequest) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

type UpdateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *UserInfo              `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUserResponse) Reset() {
	*x = UpdateUserResponse{}
	mi := &file_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserResponse) ProtoMessage() {}

func (x *UpdateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserResponse) GetUser() *UserInfo {
	if x != nil {
		return x.User
	}
	return nil
}

type LoginByCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByCodeRequest) Reset() {
	*x = LoginByCodeRequest{}
	mi := &file_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByCodeRequest) ProtoMessage() {}

func (x *LoginByCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByCodeRequest.ProtoReflect.Descriptor instead.
func (*LoginByCodeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{9}
}

func (x *LoginByCodeRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type LoginByCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginByCodeResponse) Reset() {
	*x = LoginByCodeResponse{}
	mi := &file_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginByCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginByCodeResponse) ProtoMessage() {}

func (x *LoginByCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginByCodeResponse.ProtoReflect.Descriptor instead.
func (*LoginByCodeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{10}
}

func (x *LoginByCodeResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LoginByCodeResponse) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type ForgetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Phone         string                 `protobuf:"bytes,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordRequest) Reset() {
	*x = ForgetPasswordRequest{}
	mi := &file_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordRequest) ProtoMessage() {}

func (x *ForgetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ForgetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{11}
}

func (x *ForgetPasswordRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *ForgetPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ForgetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid           uint64                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForgetPasswordResponse) Reset() {
	*x = ForgetPasswordResponse{}
	mi := &file_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForgetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgetPasswordResponse) ProtoMessage() {}

func (x *ForgetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ForgetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{12}
}

func (x *ForgetPasswordResponse) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ForgetPasswordResponse) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

// 钱包信息
type WalletInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                      // 用户ID
	Balance       int64                  `protobuf:"varint,2,opt,name=balance,proto3" json:"balance,omitempty"`                                  // 帅币可用余额
	FrozenBalance int64                  `protobuf:"varint,3,opt,name=frozen_balance,json=frozenBalance,proto3" json:"frozen_balance,omitempty"` // 冻结帅币余额（预留）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalletInfo) Reset() {
	*x = WalletInfo{}
	mi := &file_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalletInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletInfo) ProtoMessage() {}

func (x *WalletInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletInfo.ProtoReflect.Descriptor instead.
func (*WalletInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{13}
}

func (x *WalletInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *WalletInfo) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *WalletInfo) GetFrozenBalance() int64 {
	if x != nil {
		return x.FrozenBalance
	}
	return 0
}

// 查询钱包
type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{14}
}

func (x *GetWalletRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletInfo            `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{15}
}

func (x *GetWalletResponse) GetWallet() *WalletInfo {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// 充值帅币（现金 -> 帅币），这里只处理“加币”，实际支付回调可以在上游确认后调用此接口
type RechargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // 用户ID
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                            // 充值帅币数量（正数）
	BizOrderId    string                 `protobuf:"bytes,3,opt,name=biz_order_id,json=bizOrderId,proto3" json:"biz_order_id,omitempty"` // 关联的支付单号 / 业务订单号
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`                             // 备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeRequest) Reset() {
	*x = RechargeRequest{}
	mi := &file_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeRequest) ProtoMessage() {}

func (x *RechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeRequest.ProtoReflect.Descriptor instead.
func (*RechargeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{16}
}

func (x *RechargeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RechargeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeRequest) GetBizOrderId() string {
	if x != nil {
		return x.BizOrderId
	}
	return ""
}

func (x *RechargeRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type RechargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletInfo            `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"` // 充值后的最新钱包信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RechargeResponse) Reset() {
	*x = RechargeResponse{}
	mi := &file_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeResponse) ProtoMessage() {}

func (x *RechargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeResponse.ProtoReflect.Descriptor instead.
func (*RechargeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{17}
}

func (x *RechargeResponse) GetWallet() *WalletInfo {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// 消费帅币（支付订单时扣减帅币）
type ConsumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`              // 用户ID
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`                            // 消费帅币数量（正数，服务内部会按负数写流水）
	BizOrderId    string                 `protobuf:"bytes,3,opt,name=biz_order_id,json=bizOrderId,proto3" json:"biz_order_id,omitempty"` // 关联的业务订单号
	Remark        string                 `protobuf:"bytes,4,opt,name=remark,proto3" json:"remark,omitempty"`                             // 备注
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{18}
}

func (x *ConsumeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ConsumeRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConsumeRequest) GetBizOrderId() string {
	if x != nil {
		return x.BizOrderId
	}
	return ""
}

func (x *ConsumeRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

type ConsumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *WalletInfo            `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"` // 扣减后的最新钱包信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeResponse) Reset() {
	*x = ConsumeResponse{}
	mi := &file_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeResponse) ProtoMessage() {}

func (x *ConsumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeResponse.ProtoReflect.Descriptor instead.
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{19}
}

func (x *ConsumeResponse) GetWallet() *WalletInfo {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// 陪玩信息
type CompanionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 用户ID
	GameSkill     string                 `protobuf:"bytes,2,opt,name=game_skill,json=gameSkill,proto3" json:"game_skill,omitempty"`             // 游戏技能（单个游戏名称）
	PricePerHour  int64                  `protobuf:"varint,3,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"` // 每小时价格（帅币）
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                                   // 状态：0=离线, 1=在线, 2=忙碌
	Rating        float64                `protobuf:"fixed64,5,opt,name=rating,proto3" json:"rating,omitempty"`                                  // 评分（0-5分）
	TotalOrders   int64                  `protobuf:"varint,6,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"`      // 总接单数
	IsVerified    bool                   `protobuf:"varint,7,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`         // 是否认证
	AvatarUrl     string                 `protobuf:"bytes,8,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`             // 头像URL
	Bio           string                 `protobuf:"bytes,9,opt,name=bio,proto3" json:"bio,omitempty"`                                          // 个人简介
	Nickname      string                 `protobuf:"bytes,10,opt,name=nickname,proto3" json:"nickname,omitempty"`                               // 昵称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanionInfo) Reset() {
	*x = CompanionInfo{}
	mi := &file_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionInfo) ProtoMessage() {}

func (x *CompanionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionInfo.ProtoReflect.Descriptor instead.
func (*CompanionInfo) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{20}
}

func (x *CompanionInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompanionInfo) GetGameSkill() string {
	if x != nil {
		return x.GameSkill
	}
	return ""
}

func (x *CompanionInfo) GetPricePerHour() int64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *CompanionInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CompanionInfo) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CompanionInfo) GetTotalOrders() int64 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *CompanionInfo) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *CompanionInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CompanionInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

func (x *CompanionInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

// ------------- 游戏技能（词典）相关 -------------
type GameSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // 技能ID
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // 技能名称（唯一）
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 描述（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSkill) Reset() {
	*x = GameSkill{}
	mi := &file_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSkill) ProtoMessage() {}

func (x *GameSkill) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSkill.ProtoReflect.Descriptor instead.
func (*GameSkill) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{21}
}

func (x *GameSkill) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameSkill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GameSkill) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListGameSkillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGameSkillsRequest) Reset() {
	*x = ListGameSkillsRequest{}
	mi := &file_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGameSkillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameSkillsRequest) ProtoMessage() {}

func (x *ListGameSkillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameSkillsRequest.ProtoReflect.Descriptor instead.
func (*ListGameSkillsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{22}
}

type ListGameSkillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skills        []*GameSkill           `protobuf:"bytes,1,rep,name=skills,proto3" json:"skills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGameSkillsResponse) Reset() {
	*x = ListGameSkillsResponse{}
	mi := &file_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGameSkillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGameSkillsResponse) ProtoMessage() {}

func (x *ListGameSkillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGameSkillsResponse.ProtoReflect.Descriptor instead.
func (*ListGameSkillsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{23}
}

func (x *ListGameSkillsResponse) GetSkills() []*GameSkill {
	if x != nil {
		return x.Skills
	}
	return nil
}

type CreateGameSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 技能名称（必填，唯一）
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 描述（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameSkillRequest) Reset() {
	*x = CreateGameSkillRequest{}
	mi := &file_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameSkillRequest) ProtoMessage() {}

func (x *CreateGameSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameSkillRequest.ProtoReflect.Descriptor instead.
func (*CreateGameSkillRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{24}
}

func (x *CreateGameSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGameSkillRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateGameSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *GameSkill             `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGameSkillResponse) Reset() {
	*x = CreateGameSkillResponse{}
	mi := &file_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGameSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGameSkillResponse) ProtoMessage() {}

func (x *CreateGameSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGameSkillResponse.ProtoReflect.Descriptor instead.
func (*CreateGameSkillResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{25}
}

func (x *CreateGameSkillResponse) GetSkill() *GameSkill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type UpdateGameSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                  // 技能ID（必填）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // 技能名称（必填，唯一）
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // 描述（可选）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameSkillRequest) Reset() {
	*x = UpdateGameSkillRequest{}
	mi := &file_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameSkillRequest) ProtoMessage() {}

func (x *UpdateGameSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameSkillRequest.ProtoReflect.Descriptor instead.
func (*UpdateGameSkillRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateGameSkillRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateGameSkillRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGameSkillRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type UpdateGameSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skill         *GameSkill             `protobuf:"bytes,1,opt,name=skill,proto3" json:"skill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGameSkillResponse) Reset() {
	*x = UpdateGameSkillResponse{}
	mi := &file_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGameSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGameSkillResponse) ProtoMessage() {}

func (x *UpdateGameSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGameSkillResponse.ProtoReflect.Descriptor instead.
func (*UpdateGameSkillResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateGameSkillResponse) GetSkill() *GameSkill {
	if x != nil {
		return x.Skill
	}
	return nil
}

type DeleteGameSkillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` // 技能ID（必填）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameSkillRequest) Reset() {
	*x = DeleteGameSkillRequest{}
	mi := &file_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameSkillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameSkillRequest) ProtoMessage() {}

func (x *DeleteGameSkillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameSkillRequest.ProtoReflect.Descriptor instead.
func (*DeleteGameSkillRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteGameSkillRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteGameSkillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGameSkillResponse) Reset() {
	*x = DeleteGameSkillResponse{}
	mi := &file_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGameSkillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGameSkillResponse) ProtoMessage() {}

func (x *DeleteGameSkillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGameSkillResponse.ProtoReflect.Descriptor instead.
func (*DeleteGameSkillResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteGameSkillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 获取陪玩信息
type GetCompanionProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanionProfileRequest) Reset() {
	*x = GetCompanionProfileRequest{}
	mi := &file_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanionProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanionProfileRequest) ProtoMessage() {}

func (x *GetCompanionProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanionProfileRequest.ProtoReflect.Descriptor instead.
func (*GetCompanionProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{30}
}

func (x *GetCompanionProfileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCompanionProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *CompanionInfo         `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanionProfileResponse) Reset() {
	*x = GetCompanionProfileResponse{}
	mi := &file_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanionProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanionProfileResponse) ProtoMessage() {}

func (x *GetCompanionProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanionProfileResponse.ProtoReflect.Descriptor instead.
func (*GetCompanionProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{31}
}

func (x *GetCompanionProfileResponse) GetProfile() *CompanionInfo {
	if x != nil {
		return x.Profile
	}
	return nil
}

// 更新陪玩信息
type UpdateCompanionProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                     // 用户ID（必填）
	GameSkill     string                 `protobuf:"bytes,2,opt,name=game_skill,json=gameSkill,proto3" json:"game_skill,omitempty"`             // 可选，游戏技能（单个游戏名称）
	PricePerHour  int64                  `protobuf:"varint,3,opt,name=price_per_hour,json=pricePerHour,proto3" json:"price_per_hour,omitempty"` // 可选，每小时价格（帅币）
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                                   // 可选，状态：0=离线, 1=在线, 2=忙碌
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanionProfileRequest) Reset() {
	*x = UpdateCompanionProfileRequest{}
	mi := &file_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanionProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanionProfileRequest) ProtoMessage() {}

func (x *UpdateCompanionProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanionProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanionProfileRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateCompanionProfileRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCompanionProfileRequest) GetGameSkill() string {
	if x != nil {
		return x.GameSkill
	}
	return ""
}

func (x *UpdateCompanionProfileRequest) GetPricePerHour() int64 {
	if x != nil {
		return x.PricePerHour
	}
	return 0
}

func (x *UpdateCompanionProfileRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type UpdateCompanionProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *CompanionInfo         `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanionProfileResponse) Reset() {
	*x = UpdateCompanionProfileResponse{}
	mi := &file_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanionProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanionProfileResponse) ProtoMessage() {}

func (x *UpdateCompanionProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanionProfileResponse.ProtoReflect.Descriptor instead.
func (*UpdateCompanionProfileResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateCompanionProfileResponse) GetProfile() *CompanionInfo {
	if x != nil {
		return x.Profile
	}
	return nil
}

// 更新陪玩统计信息（评分 & 接单数）
type UpdateCompanionStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 用户ID（陪玩）
	DeltaOrders   int64                  `protobuf:"varint,2,opt,name=delta_orders,json=deltaOrders,proto3" json:"delta_orders,omitempty"` // 接单数增量（一般为1）
	NewRating     float64                `protobuf:"fixed64,3,opt,name=new_rating,json=newRating,proto3" json:"new_rating,omitempty"`      // 本次订单评分（0-5）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanionStatsRequest) Reset() {
	*x = UpdateCompanionStatsRequest{}
	mi := &file_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanionStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanionStatsRequest) ProtoMessage() {}

func (x *UpdateCompanionStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanionStatsRequest.ProtoReflect.Descriptor instead.
func (*UpdateCompanionStatsRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateCompanionStatsRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UpdateCompanionStatsRequest) GetDeltaOrders() int64 {
	if x != nil {
		return x.DeltaOrders
	}
	return 0
}

func (x *UpdateCompanionStatsRequest) GetNewRating() float64 {
	if x != nil {
		return x.NewRating
	}
	return 0
}

type UpdateCompanionStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *CompanionInfo         `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCompanionStatsResponse) Reset() {
	*x = UpdateCompanionStatsResponse{}
	mi := &file_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCompanionStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCompanionStatsResponse) ProtoMessage() {}

func (x *UpdateCompanionStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCompanionStatsResponse.ProtoReflect.Descriptor instead.
func (*UpdateCompanionStatsResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateCompanionStatsResponse) GetProfile() *CompanionInfo {
	if x != nil {
		return x.Profile
	}
	return nil
}

// 获取陪玩列表（用于订单匹配）
type GetCompanionListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameSkill     string                 `protobuf:"bytes,1,opt,name=game_skill,json=gameSkill,proto3" json:"game_skill,omitempty"`     // 可选，游戏技能筛选（单个游戏名称）
	MinPrice      int32                  `protobuf:"varint,2,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`       // 可选，最低价格
	MaxPrice      int32                  `protobuf:"varint,3,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`       // 可选，最高价格
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                           // 可选，状态筛选：0=离线, 1=在线, 2=忙碌（默认只返回在线）
	IsVerified    bool                   `protobuf:"varint,5,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"` // 可选，是否只返回认证陪玩
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`                               // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`       // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanionListRequest) Reset() {
	*x = GetCompanionListRequest{}
	mi := &file_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanionListRequest) ProtoMessage() {}

func (x *GetCompanionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanionListRequest.ProtoReflect.Descriptor instead.
func (*GetCompanionListRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{36}
}

func (x *GetCompanionListRequest) GetGameSkill() string {
	if x != nil {
		return x.GameSkill
	}
	return ""
}

func (x *GetCompanionListRequest) GetMinPrice() int32 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *GetCompanionListRequest) GetMaxPrice() int32 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *GetCompanionListRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *GetCompanionListRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *GetCompanionListRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCompanionListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCompanionListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Companions    []*CompanionInfo       `protobuf:"bytes,1,rep,name=companions,proto3" json:"companions,omitempty"`              // 陪玩列表
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanionListResponse) Reset() {
	*x = GetCompanionListResponse{}
	mi := &file_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanionListResponse) ProtoMessage() {}

func (x *GetCompanionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanionListResponse.ProtoReflect.Descriptor instead.
func (*GetCompanionListResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{37}
}

func (x *GetCompanionListResponse) GetCompanions() []*CompanionInfo {
	if x != nil {
		return x.Companions
	}
	return nil
}

func (x *GetCompanionListResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCompanionListResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCompanionListResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 陪玩排名项
type CompanionRankingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                // 用户ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                           // 昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`        // 头像URL
	Rating        float64                `protobuf:"fixed64,4,opt,name=rating,proto3" json:"rating,omitempty"`                             // 评分（用于评分排名）
	TotalOrders   int64                  `protobuf:"varint,5,opt,name=total_orders,json=totalOrders,proto3" json:"total_orders,omitempty"` // 总接单数（用于接单数排名）
	Rank          int32                  `protobuf:"varint,6,opt,name=rank,proto3" json:"rank,omitempty"`                                  // 排名（从1开始）
	IsVerified    bool                   `protobuf:"varint,7,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`    // 是否认证
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompanionRankingItem) Reset() {
	*x = CompanionRankingItem{}
	mi := &file_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanionRankingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanionRankingItem) ProtoMessage() {}

func (x *CompanionRankingItem) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanionRankingItem.ProtoReflect.Descriptor instead.
func (*CompanionRankingItem) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{38}
}

func (x *CompanionRankingItem) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CompanionRankingItem) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CompanionRankingItem) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *CompanionRankingItem) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CompanionRankingItem) GetTotalOrders() int64 {
	if x != nil {
		return x.TotalOrders
	}
	return 0
}

func (x *CompanionRankingItem) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CompanionRankingItem) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

// 查询陪玩评分排名
type GetCompanionRatingRankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量（默认10，最大100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanionRatingRankingRequest) Reset() {
	*x = GetCompanionRatingRankingRequest{}
	mi := &file_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanionRatingRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanionRatingRankingRequest) ProtoMessage() {}

func (x *GetCompanionRatingRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanionRatingRankingRequest.ProtoReflect.Descriptor instead.
func (*GetCompanionRatingRankingRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{39}
}

func (x *GetCompanionRatingRankingRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCompanionRatingRankingRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCompanionRatingRankingResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Rankings      []*CompanionRankingItem `protobuf:"bytes,1,rep,name=rankings,proto3" json:"rankings,omitempty"`                  // 排名列表
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	Page          int32                   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanionRatingRankingResponse) Reset() {
	*x = GetCompanionRatingRankingResponse{}
	mi := &file_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanionRatingRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanionRatingRankingResponse) ProtoMessage() {}

func (x *GetCompanionRatingRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanionRatingRankingResponse.ProtoReflect.Descriptor instead.
func (*GetCompanionRatingRankingResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{40}
}

func (x *GetCompanionRatingRankingResponse) GetRankings() []*CompanionRankingItem {
	if x != nil {
		return x.Rankings
	}
	return nil
}

func (x *GetCompanionRatingRankingResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCompanionRatingRankingResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCompanionRatingRankingResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 查询陪玩总接单数排名
type GetCompanionOrdersRankingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`                         // 页码（从1开始）
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量（默认10，最大100）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanionOrdersRankingRequest) Reset() {
	*x = GetCompanionOrdersRankingRequest{}
	mi := &file_user_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanionOrdersRankingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanionOrdersRankingRequest) ProtoMessage() {}

func (x *GetCompanionOrdersRankingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanionOrdersRankingRequest.ProtoReflect.Descriptor instead.
func (*GetCompanionOrdersRankingRequest) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{41}
}

func (x *GetCompanionOrdersRankingRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCompanionOrdersRankingRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetCompanionOrdersRankingResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Rankings      []*CompanionRankingItem `protobuf:"bytes,1,rep,name=rankings,proto3" json:"rankings,omitempty"`                  // 排名列表
	Total         int32                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`                       // 总数
	Page          int32                   `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`                         // 当前页码
	PageSize      int32                   `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"` // 每页数量
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCompanionOrdersRankingResponse) Reset() {
	*x = GetCompanionOrdersRankingResponse{}
	mi := &file_user_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCompanionOrdersRankingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCompanionOrdersRankingResponse) ProtoMessage() {}

func (x *GetCompanionOrdersRankingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCompanionOrdersRankingResponse.ProtoReflect.Descriptor instead.
func (*GetCompanionOrdersRankingResponse) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{42}
}

func (x *GetCompanionOrdersRankingResponse) GetRankings() []*CompanionRankingItem {
	if x != nil {
		return x.Rankings
	}
	return nil
}

func (x *GetCompanionOrdersRankingResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GetCompanionOrdersRankingResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCompanionOrdersRankingResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\"s\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x12\n" +
	"\x04role\x18\x04 \x01(\x05R\x04role\"4\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"1\n" +
	"\rLoginResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"H\n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\"\xe4\x01\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\x12\x18\n" +
	"\abalance\x18\b \x01(\x03R\abalance\x12%\n" +
	"\x0efrozen_balance\x18\t \x01(\x03R\rfrozenBalance\"5\n" +
	"\x0fGetUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"\xb6\x01\n" +
	"\x11UpdateUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05phone\x18\x04 \x01(\tR\x05phone\x12\x12\n" +
	"\x04role\x18\x05 \x01(\x05R\x04role\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x06 \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\a \x01(\tR\x03bio\"8\n" +
	"\x12UpdateUserResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.user.UserInfoR\x04user\"*\n" +
	"\x12LoginByCodeRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\"7\n" +
	"\x13LoginByCodeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"I\n" +
	"\x15ForgetPasswordRequest\x12\x14\n" +
	"\x05phone\x18\x01 \x01(\tR\x05phone\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\":\n" +
	"\x16ForgetPasswordResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\x04R\x03uid\"f\n" +
	"\n" +
	"WalletInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x18\n" +
	"\abalance\x18\x02 \x01(\x03R\abalance\x12%\n" +
	"\x0efrozen_balance\x18\x03 \x01(\x03R\rfrozenBalance\"+\n" +
	"\x10GetWalletRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"=\n" +
	"\x11GetWalletResponse\x12(\n" +
	"\x06wallet\x18\x01 \x01(\v2\x10.user.WalletInfoR\x06wallet\"|\n" +
	"\x0fRechargeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12 \n" +
	"\fbiz_order_id\x18\x03 \x01(\tR\n" +
	"bizOrderId\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\"<\n" +
	"\x10RechargeResponse\x12(\n" +
	"\x06wallet\x18\x01 \x01(\v2\x10.user.WalletInfoR\x06wallet\"{\n" +
	"\x0eConsumeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12 \n" +
	"\fbiz_order_id\x18\x03 \x01(\tR\n" +
	"bizOrderId\x12\x16\n" +
	"\x06remark\x18\x04 \x01(\tR\x06remark\";\n" +
	"\x0fConsumeResponse\x12(\n" +
	"\x06wallet\x18\x01 \x01(\v2\x10.user.WalletInfoR\x06wallet\"\xae\x02\n" +
	"\rCompanionInfo\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"game_skill\x18\x02 \x01(\tR\tgameSkill\x12$\n" +
	"\x0eprice_per_hour\x18\x03 \x01(\x03R\fpricePerHour\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x16\n" +
	"\x06rating\x18\x05 \x01(\x01R\x06rating\x12!\n" +
	"\ftotal_orders\x18\x06 \x01(\x03R\vtotalOrders\x12\x1f\n" +
	"\vis_verified\x18\a \x01(\bR\n" +
	"isVerified\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\b \x01(\tR\tavatarUrl\x12\x10\n" +
	"\x03bio\x18\t \x01(\tR\x03bio\x12\x1a\n" +
	"\bnickname\x18\n" +
	" \x01(\tR\bnickname\"Q\n" +
	"\tGameSkill\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"\x17\n" +
	"\x15ListGameSkillsRequest\"A\n" +
	"\x16ListGameSkillsResponse\x12'\n" +
	"\x06skills\x18\x01 \x03(\v2\x0f.user.GameSkillR\x06skills\"N\n" +
	"\x16CreateGameSkillRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"@\n" +
	"\x17CreateGameSkillResponse\x12%\n" +
	"\x05skill\x18\x01 \x01(\v2\x0f.user.GameSkillR\x05skill\"^\n" +
	"\x16UpdateGameSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"@\n" +
	"\x17UpdateGameSkillResponse\x12%\n" +
	"\x05skill\x18\x01 \x01(\v2\x0f.user.GameSkillR\x05skill\"(\n" +
	"\x16DeleteGameSkillRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"3\n" +
	"\x17DeleteGameSkillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"5\n" +
	"\x1aGetCompanionProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\"L\n" +
	"\x1bGetCompanionProfileResponse\x12-\n" +
	"\aprofile\x18\x01 \x01(\v2\x13.user.CompanionInfoR\aprofile\"\x95\x01\n" +
	"\x1dUpdateCompanionProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1d\n" +
	"\n" +
	"game_skill\x18\x02 \x01(\tR\tgameSkill\x12$\n" +
	"\x0eprice_per_hour\x18\x03 \x01(\x03R\fpricePerHour\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"O\n" +
	"\x1eUpdateCompanionProfileResponse\x12-\n" +
	"\aprofile\x18\x01 \x01(\v2\x13.user.CompanionInfoR\aprofile\"x\n" +
	"\x1bUpdateCompanionStatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12!\n" +
	"\fdelta_orders\x18\x02 \x01(\x03R\vdeltaOrders\x12\x1d\n" +
	"\n" +
	"new_rating\x18\x03 \x01(\x01R\tnewRating\"M\n" +
	"\x1cUpdateCompanionStatsResponse\x12-\n" +
	"\aprofile\x18\x01 \x01(\v2\x13.user.CompanionInfoR\aprofile\"\xdc\x01\n" +
	"\x17GetCompanionListRequest\x12\x1d\n" +
	"\n" +
	"game_skill\x18\x01 \x01(\tR\tgameSkill\x12\x1b\n" +
	"\tmin_price\x18\x02 \x01(\x05R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\x03 \x01(\x05R\bmaxPrice\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1f\n" +
	"\vis_verified\x18\x05 \x01(\bR\n" +
	"isVerified\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"\x96\x01\n" +
	"\x18GetCompanionListResponse\x123\n" +
	"\n" +
	"companions\x18\x01 \x03(\v2\x13.user.CompanionInfoR\n" +
	"companions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xda\x01\n" +
	"\x14CompanionRankingItem\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x04R\x06userId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x16\n" +
	"\x06rating\x18\x04 \x01(\x01R\x06rating\x12!\n" +
	"\ftotal_orders\x18\x05 \x01(\x03R\vtotalOrders\x12\x12\n" +
	"\x04rank\x18\x06 \x01(\x05R\x04rank\x12\x1f\n" +
	"\vis_verified\x18\a \x01(\bR\n" +
	"isVerified\"S\n" +
	" GetCompanionRatingRankingRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xa2\x01\n" +
	"!GetCompanionRatingRankingResponse\x126\n" +
	"\brankings\x18\x01 \x03(\v2\x1a.user.CompanionRankingItemR\brankings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"S\n" +
	" GetCompanionOrdersRankingRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\xa2\x01\n" +
	"!GetCompanionOrdersRankingResponse\x126\n" +
	"\brankings\x18\x01 \x03(\v2\x1a.user.CompanionRankingItemR\brankings\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize2\xba\v\n" +
	"\x04User\x129\n" +
	"\bRegister\x12\x15.user.RegisterRequest\x1a\x16.user.RegisterResponse\x120\n" +
	"\x05Login\x12\x12.user.LoginRequest\x1a\x13.user.LoginResponse\x126\n" +
	"\aGetUser\x12\x14.user.GetUserRequest\x1a\x15.user.GetUserResponse\x12?\n" +
	"\n" +
	"UpdateUser\x12\x17.user.UpdateUserRequest\x1a\x18.user.UpdateUserResponse\x12B\n" +
	"\vLoginByCode\x12\x18.user.LoginByCodeRequest\x1a\x19.user.LoginByCodeResponse\x12K\n" +
	"\x0eForgetPassword\x12\x1b.user.ForgetPasswordRequest\x1a\x1c.user.ForgetPasswordResponse\x12<\n" +
	"\tGetWallet\x12\x16.user.GetWalletRequest\x1a\x17.user.GetWalletResponse\x129\n" +
	"\bRecharge\x12\x15.user.RechargeRequest\x1a\x16.user.RechargeResponse\x126\n" +
	"\aConsume\x12\x14.user.ConsumeRequest\x1a\x15.user.ConsumeResponse\x12Z\n" +
	"\x13GetCompanionProfile\x12 .user.GetCompanionProfileRequest\x1a!.user.GetCompanionProfileResponse\x12c\n" +
	"\x16UpdateCompanionProfile\x12#.user.UpdateCompanionProfileRequest\x1a$.user.UpdateCompanionProfileResponse\x12]\n" +
	"\x14UpdateCompanionStats\x12!.user.UpdateCompanionStatsRequest\x1a\".user.UpdateCompanionStatsResponse\x12Q\n" +
	"\x10GetCompanionList\x12\x1d.user.GetCompanionListRequest\x1a\x1e.user.GetCompanionListResponse\x12l\n" +
	"\x19GetCompanionRatingRanking\x12&.user.GetCompanionRatingRankingRequest\x1a'.user.GetCompanionRatingRankingResponse\x12l\n" +
	"\x19GetCompanionOrdersRanking\x12&.user.GetCompanionOrdersRankingRequest\x1a'.user.GetCompanionOrdersRankingResponse\x12K\n" +
	"\x0eListGameSkills\x12\x1b.user.ListGameSkillsRequest\x1a\x1c.user.ListGameSkillsResponse\x12N\n" +
	"\x0fCreateGameSkill\x12\x1c.user.CreateGameSkillRequest\x1a\x1d.user.CreateGameSkillResponse\x12N\n" +
	"\x0fUpdateGameSkill\x12\x1c.user.UpdateGameSkillRequest\x1a\x1d.user.UpdateGameSkillResponse\x12N\n" +
	"\x0fDeleteGameSkill\x12\x1c.user.DeleteGameSkillRequest\x1a\x1d.user.DeleteGameSkillResponseB\bZ\x06./userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_user_proto_goTypes = []any{
	(*RegisterRequest)(nil),                   // 0: user.RegisterRequest
	(*RegisterResponse)(nil),                  // 1: user.RegisterResponse
	(*LoginRequest)(nil),                      // 2: user.LoginRequest
	(*LoginResponse)(nil),                     // 3: user.LoginResponse
	(*GetUserRequest)(nil),                    // 4: user.GetUserRequest
	(*UserInfo)(nil),                          // 5: user.UserInfo
	(*GetUserResponse)(nil),                   // 6: user.GetUserResponse
	(*UpdateUserRequest)(nil),                 // 7: user.UpdateUserRequest
	(*UpdateUserResponse)(nil),                // 8: user.UpdateUserResponse
	(*LoginByCodeRequest)(nil),                // 9: user.LoginByCodeRequest
	(*LoginByCodeResponse)(nil),               // 10: user.LoginByCodeResponse
	(*ForgetPasswordRequest)(nil),             // 11: user.ForgetPasswordRequest
	(*ForgetPasswordResponse)(nil),            // 12: user.ForgetPasswordResponse
	(*WalletInfo)(nil),                        // 13: user.WalletInfo
	(*GetWalletRequest)(nil),                  // 14: user.GetWalletRequest
	(*GetWalletResponse)(nil),                 // 15: user.GetWalletResponse
	(*RechargeRequest)(nil),                   // 16: user.RechargeRequest
	(*RechargeResponse)(nil),                  // 17: user.RechargeResponse
	(*ConsumeRequest)(nil),                    // 18: user.ConsumeRequest
	(*ConsumeResponse)(nil),                   // 19: user.ConsumeResponse
	(*CompanionInfo)(nil),                     // 20: user.CompanionInfo
	(*GameSkill)(nil),                         // 21: user.GameSkill
	(*ListGameSkillsRequest)(nil),             // 22: user.ListGameSkillsRequest
	(*ListGameSkillsResponse)(nil),            // 23: user.ListGameSkillsResponse
	(*CreateGameSkillRequest)(nil),            // 24: user.CreateGameSkillRequest
	(*CreateGameSkillResponse)(nil),           // 25: user.CreateGameSkillResponse
	(*UpdateGameSkillRequest)(nil),            // 26: user.UpdateGameSkillRequest
	(*UpdateGameSkillResponse)(nil),           // 27: user.UpdateGameSkillResponse
	(*DeleteGameSkillRequest)(nil),            // 28: user.DeleteGameSkillRequest
	(*DeleteGameSkillResponse)(nil),           // 29: user.DeleteGameSkillResponse
	(*GetCompanionProfileRequest)(nil),        // 30: user.GetCompanionProfileRequest
	(*GetCompanionProfileResponse)(nil),       // 31: user.GetCompanionProfileResponse
	(*UpdateCompanionProfileRequest)(nil),     // 32: user.UpdateCompanionProfileRequest
	(*UpdateCompanionProfileResponse)(nil),    // 33: user.UpdateCompanionProfileResponse
	(*UpdateCompanionStatsRequest)(nil),       // 34: user.UpdateCompanionStatsRequest
	(*UpdateCompanionStatsResponse)(nil),      // 35: user.UpdateCompanionStatsResponse
	(*GetCompanionListRequest)(nil),           // 36: user.GetCompanionListRequest
	(*GetCompanionListResponse)(nil),          // 37: user.GetCompanionListResponse
	(*CompanionRankingItem)(nil),              // 38: user.CompanionRankingItem
	(*GetCompanionRatingRankingRequest)(nil),  // 39: user.GetCompanionRatingRankingRequest
	(*GetCompanionRatingRankingResponse)(nil), // 40: user.GetCompanionRatingRankingResponse
	(*GetCompanionOrdersRankingRequest)(nil),  // 41: user.GetCompanionOrdersRankingRequest
	(*GetCompanionOrdersRankingResponse)(nil), // 42: user.GetCompanionOrdersRankingResponse
}
var file_user_proto_depIdxs = []int32{
	5,  // 0: user.GetUserResponse.user:type_name -> user.UserInfo
	5,  // 1: user.UpdateUserResponse.user:type_name -> user.UserInfo
	13, // 2: user.GetWalletResponse.wallet:type_name -> user.WalletInfo
	13, // 3: user.RechargeResponse.wallet:type_name -> user.WalletInfo
	13, // 4: user.ConsumeResponse.wallet:type_name -> user.WalletInfo
	21, // 5: user.ListGameSkillsResponse.skills:type_name -> user.GameSkill
	21, // 6: user.CreateGameSkillResponse.skill:type_name -> user.GameSkill
	21, // 7: user.UpdateGameSkillResponse.skill:type_name -> user.GameSkill
	20, // 8: user.GetCompanionProfileResponse.profile:type_name -> user.CompanionInfo
	20, // 9: user.UpdateCompanionProfileResponse.profile:type_name -> user.CompanionInfo
	20, // 10: user.UpdateCompanionStatsResponse.profile:type_name -> user.CompanionInfo
	20, // 11: user.GetCompanionListResponse.companions:type_name -> user.CompanionInfo
	38, // 12: user.GetCompanionRatingRankingResponse.rankings:type_name -> user.CompanionRankingItem
	38, // 13: user.GetCompanionOrdersRankingResponse.rankings:type_name -> user.CompanionRankingItem
	0,  // 14: user.User.Register:input_type -> user.RegisterRequest
	2,  // 15: user.User.Login:input_type -> user.LoginRequest
	4,  // 16: user.User.GetUser:input_type -> user.GetUserRequest
	7,  // 17: user.User.UpdateUser:input_type -> user.UpdateUserRequest
	9,  // 18: user.User.LoginByCode:input_type -> user.LoginByCodeRequest
	11, // 19: user.User.ForgetPassword:input_type -> user.ForgetPasswordRequest
	14, // 20: user.User.GetWallet:input_type -> user.GetWalletRequest
	16, // 21: user.User.Recharge:input_type -> user.RechargeRequest
	18, // 22: user.User.Consume:input_type -> user.ConsumeRequest
	30, // 23: user.User.GetCompanionProfile:input_type -> user.GetCompanionProfileRequest
	32, // 24: user.User.UpdateCompanionProfile:input_type -> user.UpdateCompanionProfileRequest
	34, // 25: user.User.UpdateCompanionStats:input_type -> user.UpdateCompanionStatsRequest
	36, // 26: user.User.GetCompanionList:input_type -> user.GetCompanionListRequest
	39, // 27: user.User.GetCompanionRatingRanking:input_type -> user.GetCompanionRatingRankingRequest
	41, // 28: user.User.GetCompanionOrdersRanking:input_type -> user.GetCompanionOrdersRankingRequest
	22, // 29: user.User.ListGameSkills:input_type -> user.ListGameSkillsRequest
	24, // 30: user.User.CreateGameSkill:input_type -> user.CreateGameSkillRequest
	26, // 31: user.User.UpdateGameSkill:input_type -> user.UpdateGameSkillRequest
	28, // 32: user.User.DeleteGameSkill:input_type -> user.DeleteGameSkillRequest
	1,  // 33: user.User.Register:output_type -> user.RegisterResponse
	3,  // 34: user.User.Login:output_type -> user.LoginResponse
	6,  // 35: user.User.GetUser:output_type -> user.GetUserResponse
	8,  // 36: user.User.UpdateUser:output_type -> user.UpdateUserResponse
	10, // 37: user.User.LoginByCode:output_type -> user.LoginByCodeResponse
	12, // 38: user.User.ForgetPassword:output_type -> user.ForgetPasswordResponse
	15, // 39: user.User.GetWallet:output_type -> user.GetWalletResponse
	17, // 40: user.User.Recharge:output_type -> user.RechargeResponse
	19, // 41: user.User.Consume:output_type -> user.ConsumeResponse
	31, // 42: user.User.GetCompanionProfile:output_type -> user.GetCompanionProfileResponse
	33, // 43: user.User.UpdateCompanionProfile:output_type -> user.UpdateCompanionProfileResponse
	35, // 44: user.User.UpdateCompanionStats:output_type -> user.UpdateCompanionStatsResponse
	37, // 45: user.User.GetCompanionList:output_type -> user.GetCompanionListResponse
	40, // 46: user.User.GetCompanionRatingRanking:output_type -> user.GetCompanionRatingRankingResponse
	42, // 47: user.User.GetCompanionOrdersRanking:output_type -> user.GetCompanionOrdersRankingResponse
	23, // 48: user.User.ListGameSkills:output_type -> user.ListGameSkillsResponse
	25, // 49: user.User.CreateGameSkill:output_type -> user.CreateGameSkillResponse
	27, // 50: user.User.UpdateGameSkill:output_type -> user.UpdateGameSkillResponse
	29, // 51: user.User.DeleteGameSkill:output_type -> user.DeleteGameSkillResponse
	33, // [33:52] is the sub-list for method output_type
	14, // [14:33] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
