// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	User_Register_FullMethodName                  = "/user.User/Register"
	User_Login_FullMethodName                     = "/user.User/Login"
	User_GetUser_FullMethodName                   = "/user.User/GetUser"
	User_UpdateUser_FullMethodName                = "/user.User/UpdateUser"
	User_LoginByCode_FullMethodName               = "/user.User/LoginByCode"
	User_ForgetPassword_FullMethodName            = "/user.User/ForgetPassword"
	User_ChangePhone_FullMethodName               = "/user.User/ChangePhone"
	User_ChangePassword_FullMethodName            = "/user.User/ChangePassword"
	User_GetWallet_FullMethodName                 = "/user.User/GetWallet"
	User_Recharge_FullMethodName                  = "/user.User/Recharge"
	User_Consume_FullMethodName                   = "/user.User/Consume"
	User_CreateRechargeOrder_FullMethodName       = "/user.User/CreateRechargeOrder"
	User_UpdateRechargeOrderStatus_FullMethodName = "/user.User/UpdateRechargeOrderStatus"
	User_RechargeList_FullMethodName              = "/user.User/RechargeList"
	User_GetCompanionProfile_FullMethodName       = "/user.User/GetCompanionProfile"
	User_UpdateCompanionProfile_FullMethodName    = "/user.User/UpdateCompanionProfile"
	User_UpdateCompanionStats_FullMethodName      = "/user.User/UpdateCompanionStats"
	User_GetCompanionList_FullMethodName          = "/user.User/GetCompanionList"
	User_GetCompanionRatingRanking_FullMethodName = "/user.User/GetCompanionRatingRanking"
	User_GetCompanionOrdersRanking_FullMethodName = "/user.User/GetCompanionOrdersRanking"
	User_ListGameSkills_FullMethodName            = "/user.User/ListGameSkills"
	User_CreateGameSkill_FullMethodName           = "/user.User/CreateGameSkill"
	User_UpdateGameSkill_FullMethodName           = "/user.User/UpdateGameSkill"
	User_DeleteGameSkill_FullMethodName           = "/user.User/DeleteGameSkill"
	User_FollowUser_FullMethodName                = "/user.User/FollowUser"
	User_UnfollowUser_FullMethodName              = "/user.User/UnfollowUser"
	User_GetMyFollowingList_FullMethodName        = "/user.User/GetMyFollowingList"
	User_GetMyFollowersList_FullMethodName        = "/user.User/GetMyFollowersList"
	User_GetMutualFollowList_FullMethodName       = "/user.User/GetMutualFollowList"
	User_CheckFollowStatus_FullMethodName         = "/user.User/CheckFollowStatus"
)

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	LoginByCode(ctx context.Context, in *LoginByCodeRequest, opts ...grpc.CallOption) (*LoginByCodeResponse, error)
	ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordResponse, error)
	ChangePhone(ctx context.Context, in *ChangePhoneRequest, opts ...grpc.CallOption) (*ChangePhoneResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
	// 帅币钱包相关接口
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
	Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeResponse, error)
	Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error)
	CreateRechargeOrder(ctx context.Context, in *CreateRechargeOrderRequest, opts ...grpc.CallOption) (*CreateRechargeOrderResponse, error)
	UpdateRechargeOrderStatus(ctx context.Context, in *UpdateRechargeOrderStatusRequest, opts ...grpc.CallOption) (*UpdateRechargeOrderStatusResponse, error)
	RechargeList(ctx context.Context, in *RechargeListRequest, opts ...grpc.CallOption) (*RechargeListResponse, error)
	// 陪玩信息相关接口
	GetCompanionProfile(ctx context.Context, in *GetCompanionProfileRequest, opts ...grpc.CallOption) (*GetCompanionProfileResponse, error)
	UpdateCompanionProfile(ctx context.Context, in *UpdateCompanionProfileRequest, opts ...grpc.CallOption) (*UpdateCompanionProfileResponse, error)
	UpdateCompanionStats(ctx context.Context, in *UpdateCompanionStatsRequest, opts ...grpc.CallOption) (*UpdateCompanionStatsResponse, error)
	GetCompanionList(ctx context.Context, in *GetCompanionListRequest, opts ...grpc.CallOption) (*GetCompanionListResponse, error)
	// 陪玩排名相关接口
	GetCompanionRatingRanking(ctx context.Context, in *GetCompanionRatingRankingRequest, opts ...grpc.CallOption) (*GetCompanionRatingRankingResponse, error)
	GetCompanionOrdersRanking(ctx context.Context, in *GetCompanionOrdersRankingRequest, opts ...grpc.CallOption) (*GetCompanionOrdersRankingResponse, error)
	// 游戏技能管理接口
	ListGameSkills(ctx context.Context, in *ListGameSkillsRequest, opts ...grpc.CallOption) (*ListGameSkillsResponse, error)
	CreateGameSkill(ctx context.Context, in *CreateGameSkillRequest, opts ...grpc.CallOption) (*CreateGameSkillResponse, error)
	UpdateGameSkill(ctx context.Context, in *UpdateGameSkillRequest, opts ...grpc.CallOption) (*UpdateGameSkillResponse, error)
	DeleteGameSkill(ctx context.Context, in *DeleteGameSkillRequest, opts ...grpc.CallOption) (*DeleteGameSkillResponse, error)
	// 关注相关接口
	FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error)
	UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error)
	GetMyFollowingList(ctx context.Context, in *GetMyFollowingListRequest, opts ...grpc.CallOption) (*GetMyFollowingListResponse, error)
	GetMyFollowersList(ctx context.Context, in *GetMyFollowersListRequest, opts ...grpc.CallOption) (*GetMyFollowersListResponse, error)
	GetMutualFollowList(ctx context.Context, in *GetMutualFollowListRequest, opts ...grpc.CallOption) (*GetMutualFollowListResponse, error)
	CheckFollowStatus(ctx context.Context, in *CheckFollowStatusRequest, opts ...grpc.CallOption) (*CheckFollowStatusResponse, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, User_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, User_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, User_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, User_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) LoginByCode(ctx context.Context, in *LoginByCodeRequest, opts ...grpc.CallOption) (*LoginByCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginByCodeResponse)
	err := c.cc.Invoke(ctx, User_LoginByCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForgetPasswordResponse)
	err := c.cc.Invoke(ctx, User_ForgetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ChangePhone(ctx context.Context, in *ChangePhoneRequest, opts ...grpc.CallOption) (*ChangePhoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePhoneResponse)
	err := c.cc.Invoke(ctx, User_ChangePhone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, User_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResponse)
	err := c.cc.Invoke(ctx, User_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RechargeResponse)
	err := c.cc.Invoke(ctx, User_Recharge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsumeResponse)
	err := c.cc.Invoke(ctx, User_Consume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateRechargeOrder(ctx context.Context, in *CreateRechargeOrderRequest, opts ...grpc.CallOption) (*CreateRechargeOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRechargeOrderResponse)
	err := c.cc.Invoke(ctx, User_CreateRechargeOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateRechargeOrderStatus(ctx context.Context, in *UpdateRechargeOrderStatusRequest, opts ...grpc.CallOption) (*UpdateRechargeOrderStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRechargeOrderStatusResponse)
	err := c.cc.Invoke(ctx, User_UpdateRechargeOrderStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) RechargeList(ctx context.Context, in *RechargeListRequest, opts ...grpc.CallOption) (*RechargeListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RechargeListResponse)
	err := c.cc.Invoke(ctx, User_RechargeList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetCompanionProfile(ctx context.Context, in *GetCompanionProfileRequest, opts ...grpc.CallOption) (*GetCompanionProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompanionProfileResponse)
	err := c.cc.Invoke(ctx, User_GetCompanionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateCompanionProfile(ctx context.Context, in *UpdateCompanionProfileRequest, opts ...grpc.CallOption) (*UpdateCompanionProfileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCompanionProfileResponse)
	err := c.cc.Invoke(ctx, User_UpdateCompanionProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateCompanionStats(ctx context.Context, in *UpdateCompanionStatsRequest, opts ...grpc.CallOption) (*UpdateCompanionStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCompanionStatsResponse)
	err := c.cc.Invoke(ctx, User_UpdateCompanionStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetCompanionList(ctx context.Context, in *GetCompanionListRequest, opts ...grpc.CallOption) (*GetCompanionListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompanionListResponse)
	err := c.cc.Invoke(ctx, User_GetCompanionList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetCompanionRatingRanking(ctx context.Context, in *GetCompanionRatingRankingRequest, opts ...grpc.CallOption) (*GetCompanionRatingRankingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompanionRatingRankingResponse)
	err := c.cc.Invoke(ctx, User_GetCompanionRatingRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetCompanionOrdersRanking(ctx context.Context, in *GetCompanionOrdersRankingRequest, opts ...grpc.CallOption) (*GetCompanionOrdersRankingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCompanionOrdersRankingResponse)
	err := c.cc.Invoke(ctx, User_GetCompanionOrdersRanking_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) ListGameSkills(ctx context.Context, in *ListGameSkillsRequest, opts ...grpc.CallOption) (*ListGameSkillsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGameSkillsResponse)
	err := c.cc.Invoke(ctx, User_ListGameSkills_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CreateGameSkill(ctx context.Context, in *CreateGameSkillRequest, opts ...grpc.CallOption) (*CreateGameSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGameSkillResponse)
	err := c.cc.Invoke(ctx, User_CreateGameSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UpdateGameSkill(ctx context.Context, in *UpdateGameSkillRequest, opts ...grpc.CallOption) (*UpdateGameSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateGameSkillResponse)
	err := c.cc.Invoke(ctx, User_UpdateGameSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DeleteGameSkill(ctx context.Context, in *DeleteGameSkillRequest, opts ...grpc.CallOption) (*DeleteGameSkillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGameSkillResponse)
	err := c.cc.Invoke(ctx, User_DeleteGameSkill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FollowUserResponse)
	err := c.cc.Invoke(ctx, User_FollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnfollowUserResponse)
	err := c.cc.Invoke(ctx, User_UnfollowUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetMyFollowingList(ctx context.Context, in *GetMyFollowingListRequest, opts ...grpc.CallOption) (*GetMyFollowingListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyFollowingListResponse)
	err := c.cc.Invoke(ctx, User_GetMyFollowingList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetMyFollowersList(ctx context.Context, in *GetMyFollowersListRequest, opts ...grpc.CallOption) (*GetMyFollowersListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyFollowersListResponse)
	err := c.cc.Invoke(ctx, User_GetMyFollowersList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetMutualFollowList(ctx context.Context, in *GetMutualFollowListRequest, opts ...grpc.CallOption) (*GetMutualFollowListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMutualFollowListResponse)
	err := c.cc.Invoke(ctx, User_GetMutualFollowList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) CheckFollowStatus(ctx context.Context, in *CheckFollowStatusRequest, opts ...grpc.CallOption) (*CheckFollowStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckFollowStatusResponse)
	err := c.cc.Invoke(ctx, User_CheckFollowStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility.
type UserServer interface {
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	LoginByCode(context.Context, *LoginByCodeRequest) (*LoginByCodeResponse, error)
	ForgetPassword(context.Context, *ForgetPasswordRequest) (*ForgetPasswordResponse, error)
	ChangePhone(context.Context, *ChangePhoneRequest) (*ChangePhoneResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	// 帅币钱包相关接口
	GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error)
	Recharge(context.Context, *RechargeRequest) (*RechargeResponse, error)
	Consume(context.Context, *ConsumeRequest) (*ConsumeResponse, error)
	CreateRechargeOrder(context.Context, *CreateRechargeOrderRequest) (*CreateRechargeOrderResponse, error)
	UpdateRechargeOrderStatus(context.Context, *UpdateRechargeOrderStatusRequest) (*UpdateRechargeOrderStatusResponse, error)
	RechargeList(context.Context, *RechargeListRequest) (*RechargeListResponse, error)
	// 陪玩信息相关接口
	GetCompanionProfile(context.Context, *GetCompanionProfileRequest) (*GetCompanionProfileResponse, error)
	UpdateCompanionProfile(context.Context, *UpdateCompanionProfileRequest) (*UpdateCompanionProfileResponse, error)
	UpdateCompanionStats(context.Context, *UpdateCompanionStatsRequest) (*UpdateCompanionStatsResponse, error)
	GetCompanionList(context.Context, *GetCompanionListRequest) (*GetCompanionListResponse, error)
	// 陪玩排名相关接口
	GetCompanionRatingRanking(context.Context, *GetCompanionRatingRankingRequest) (*GetCompanionRatingRankingResponse, error)
	GetCompanionOrdersRanking(context.Context, *GetCompanionOrdersRankingRequest) (*GetCompanionOrdersRankingResponse, error)
	// 游戏技能管理接口
	ListGameSkills(context.Context, *ListGameSkillsRequest) (*ListGameSkillsResponse, error)
	CreateGameSkill(context.Context, *CreateGameSkillRequest) (*CreateGameSkillResponse, error)
	UpdateGameSkill(context.Context, *UpdateGameSkillRequest) (*UpdateGameSkillResponse, error)
	DeleteGameSkill(context.Context, *DeleteGameSkillRequest) (*DeleteGameSkillResponse, error)
	// 关注相关接口
	FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error)
	UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error)
	GetMyFollowingList(context.Context, *GetMyFollowingListRequest) (*GetMyFollowingListResponse, error)
	GetMyFollowersList(context.Context, *GetMyFollowersListRequest) (*GetMyFollowersListResponse, error)
	GetMutualFollowList(context.Context, *GetMutualFollowListRequest) (*GetMutualFollowListResponse, error)
	CheckFollowStatus(context.Context, *CheckFollowStatusRequest) (*CheckFollowStatusResponse, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServer struct{}

func (UnimplementedUserServer) Register(context.Context, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServer) GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedUserServer) UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedUserServer) LoginByCode(context.Context, *LoginByCodeRequest) (*LoginByCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginByCode not implemented")
}
func (UnimplementedUserServer) ForgetPassword(context.Context, *ForgetPasswordRequest) (*ForgetPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForgetPassword not implemented")
}
func (UnimplementedUserServer) ChangePhone(context.Context, *ChangePhoneRequest) (*ChangePhoneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePhone not implemented")
}
func (UnimplementedUserServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedUserServer) GetWallet(context.Context, *GetWalletRequest) (*GetWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedUserServer) Recharge(context.Context, *RechargeRequest) (*RechargeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Recharge not implemented")
}
func (UnimplementedUserServer) Consume(context.Context, *ConsumeRequest) (*ConsumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Consume not implemented")
}
func (UnimplementedUserServer) CreateRechargeOrder(context.Context, *CreateRechargeOrderRequest) (*CreateRechargeOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRechargeOrder not implemented")
}
func (UnimplementedUserServer) UpdateRechargeOrderStatus(context.Context, *UpdateRechargeOrderStatusRequest) (*UpdateRechargeOrderStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRechargeOrderStatus not implemented")
}
func (UnimplementedUserServer) RechargeList(context.Context, *RechargeListRequest) (*RechargeListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RechargeList not implemented")
}
func (UnimplementedUserServer) GetCompanionProfile(context.Context, *GetCompanionProfileRequest) (*GetCompanionProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanionProfile not implemented")
}
func (UnimplementedUserServer) UpdateCompanionProfile(context.Context, *UpdateCompanionProfileRequest) (*UpdateCompanionProfileResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCompanionProfile not implemented")
}
func (UnimplementedUserServer) UpdateCompanionStats(context.Context, *UpdateCompanionStatsRequest) (*UpdateCompanionStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCompanionStats not implemented")
}
func (UnimplementedUserServer) GetCompanionList(context.Context, *GetCompanionListRequest) (*GetCompanionListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanionList not implemented")
}
func (UnimplementedUserServer) GetCompanionRatingRanking(context.Context, *GetCompanionRatingRankingRequest) (*GetCompanionRatingRankingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanionRatingRanking not implemented")
}
func (UnimplementedUserServer) GetCompanionOrdersRanking(context.Context, *GetCompanionOrdersRankingRequest) (*GetCompanionOrdersRankingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCompanionOrdersRanking not implemented")
}
func (UnimplementedUserServer) ListGameSkills(context.Context, *ListGameSkillsRequest) (*ListGameSkillsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListGameSkills not implemented")
}
func (UnimplementedUserServer) CreateGameSkill(context.Context, *CreateGameSkillRequest) (*CreateGameSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGameSkill not implemented")
}
func (UnimplementedUserServer) UpdateGameSkill(context.Context, *UpdateGameSkillRequest) (*UpdateGameSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateGameSkill not implemented")
}
func (UnimplementedUserServer) DeleteGameSkill(context.Context, *DeleteGameSkillRequest) (*DeleteGameSkillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteGameSkill not implemented")
}
func (UnimplementedUserServer) FollowUser(context.Context, *FollowUserRequest) (*FollowUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FollowUser not implemented")
}
func (UnimplementedUserServer) UnfollowUser(context.Context, *UnfollowUserRequest) (*UnfollowUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnfollowUser not implemented")
}
func (UnimplementedUserServer) GetMyFollowingList(context.Context, *GetMyFollowingListRequest) (*GetMyFollowingListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyFollowingList not implemented")
}
func (UnimplementedUserServer) GetMyFollowersList(context.Context, *GetMyFollowersListRequest) (*GetMyFollowersListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyFollowersList not implemented")
}
func (UnimplementedUserServer) GetMutualFollowList(context.Context, *GetMutualFollowListRequest) (*GetMutualFollowListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMutualFollowList not implemented")
}
func (UnimplementedUserServer) CheckFollowStatus(context.Context, *CheckFollowStatusRequest) (*CheckFollowStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckFollowStatus not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}
func (UnimplementedUserServer) testEmbeddedByValue()              {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	// If the following call panics, it indicates UnimplementedUserServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_LoginByCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginByCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).LoginByCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_LoginByCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).LoginByCode(ctx, req.(*LoginByCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ForgetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForgetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ForgetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_ForgetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ForgetPassword(ctx, req.(*ForgetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ChangePhone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePhoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ChangePhone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_ChangePhone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ChangePhone(ctx, req.(*ChangePhoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Recharge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Recharge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Recharge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Recharge(ctx, req.(*RechargeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_Consume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).Consume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_Consume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).Consume(ctx, req.(*ConsumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateRechargeOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRechargeOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateRechargeOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CreateRechargeOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateRechargeOrder(ctx, req.(*CreateRechargeOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateRechargeOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRechargeOrderStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateRechargeOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateRechargeOrderStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateRechargeOrderStatus(ctx, req.(*UpdateRechargeOrderStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_RechargeList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RechargeListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).RechargeList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_RechargeList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).RechargeList(ctx, req.(*RechargeListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetCompanionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanionProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCompanionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetCompanionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCompanionProfile(ctx, req.(*GetCompanionProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateCompanionProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanionProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateCompanionProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateCompanionProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateCompanionProfile(ctx, req.(*UpdateCompanionProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateCompanionStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCompanionStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateCompanionStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateCompanionStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateCompanionStats(ctx, req.(*UpdateCompanionStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetCompanionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCompanionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetCompanionList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCompanionList(ctx, req.(*GetCompanionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetCompanionRatingRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanionRatingRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCompanionRatingRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetCompanionRatingRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCompanionRatingRanking(ctx, req.(*GetCompanionRatingRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetCompanionOrdersRanking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCompanionOrdersRankingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCompanionOrdersRanking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetCompanionOrdersRanking_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCompanionOrdersRanking(ctx, req.(*GetCompanionOrdersRankingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_ListGameSkills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGameSkillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).ListGameSkills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_ListGameSkills_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).ListGameSkills(ctx, req.(*ListGameSkillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CreateGameSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGameSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CreateGameSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CreateGameSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CreateGameSkill(ctx, req.(*CreateGameSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UpdateGameSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateGameSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UpdateGameSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UpdateGameSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UpdateGameSkill(ctx, req.(*UpdateGameSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DeleteGameSkill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGameSkillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DeleteGameSkill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_DeleteGameSkill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DeleteGameSkill(ctx, req.(*DeleteGameSkillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_FollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).FollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_FollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).FollowUser(ctx, req.(*FollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_UnfollowUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnfollowUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).UnfollowUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_UnfollowUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).UnfollowUser(ctx, req.(*UnfollowUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetMyFollowingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyFollowingListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetMyFollowingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetMyFollowingList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetMyFollowingList(ctx, req.(*GetMyFollowingListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetMyFollowersList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyFollowersListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetMyFollowersList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetMyFollowersList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetMyFollowersList(ctx, req.(*GetMyFollowersListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetMutualFollowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMutualFollowListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetMutualFollowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_GetMutualFollowList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetMutualFollowList(ctx, req.(*GetMutualFollowListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_CheckFollowStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckFollowStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).CheckFollowStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: User_CheckFollowStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).CheckFollowStatus(ctx, req.(*CheckFollowStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _User_Register_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _User_Login_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _User_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _User_UpdateUser_Handler,
		},
		{
			MethodName: "LoginByCode",
			Handler:    _User_LoginByCode_Handler,
		},
		{
			MethodName: "ForgetPassword",
			Handler:    _User_ForgetPassword_Handler,
		},
		{
			MethodName: "ChangePhone",
			Handler:    _User_ChangePhone_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _User_ChangePassword_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _User_GetWallet_Handler,
		},
		{
			MethodName: "Recharge",
			Handler:    _User_Recharge_Handler,
		},
		{
			MethodName: "Consume",
			Handler:    _User_Consume_Handler,
		},
		{
			MethodName: "CreateRechargeOrder",
			Handler:    _User_CreateRechargeOrder_Handler,
		},
		{
			MethodName: "UpdateRechargeOrderStatus",
			Handler:    _User_UpdateRechargeOrderStatus_Handler,
		},
		{
			MethodName: "RechargeList",
			Handler:    _User_RechargeList_Handler,
		},
		{
			MethodName: "GetCompanionProfile",
			Handler:    _User_GetCompanionProfile_Handler,
		},
		{
			MethodName: "UpdateCompanionProfile",
			Handler:    _User_UpdateCompanionProfile_Handler,
		},
		{
			MethodName: "UpdateCompanionStats",
			Handler:    _User_UpdateCompanionStats_Handler,
		},
		{
			MethodName: "GetCompanionList",
			Handler:    _User_GetCompanionList_Handler,
		},
		{
			MethodName: "GetCompanionRatingRanking",
			Handler:    _User_GetCompanionRatingRanking_Handler,
		},
		{
			MethodName: "GetCompanionOrdersRanking",
			Handler:    _User_GetCompanionOrdersRanking_Handler,
		},
		{
			MethodName: "ListGameSkills",
			Handler:    _User_ListGameSkills_Handler,
		},
		{
			MethodName: "CreateGameSkill",
			Handler:    _User_CreateGameSkill_Handler,
		},
		{
			MethodName: "UpdateGameSkill",
			Handler:    _User_UpdateGameSkill_Handler,
		},
		{
			MethodName: "DeleteGameSkill",
			Handler:    _User_DeleteGameSkill_Handler,
		},
		{
			MethodName: "FollowUser",
			Handler:    _User_FollowUser_Handler,
		},
		{
			MethodName: "UnfollowUser",
			Handler:    _User_UnfollowUser_Handler,
		},
		{
			MethodName: "GetMyFollowingList",
			Handler:    _User_GetMyFollowingList_Handler,
		},
		{
			MethodName: "GetMyFollowersList",
			Handler:    _User_GetMyFollowersList_Handler,
		},
		{
			MethodName: "GetMutualFollowList",
			Handler:    _User_GetMutualFollowList_Handler,
		},
		{
			MethodName: "CheckFollowStatus",
			Handler:    _User_CheckFollowStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
