// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: agent.proto

package agentclient

import (
	"context"

	"SLGaming/back/services/agent/agent"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetMessageHistoryRequest  = agent.GetMessageHistoryRequest
	GetMessageHistoryResponse = agent.GetMessageHistoryResponse
	GetSessionListRequest     = agent.GetSessionListRequest
	GetSessionListResponse    = agent.GetSessionListResponse
	MessageInfo               = agent.MessageInfo
	PingRequest               = agent.PingRequest
	PingResponse              = agent.PingResponse
	SendMessageRequest        = agent.SendMessageRequest
	SendMessageResponse       = agent.SendMessageResponse
	SessionInfo               = agent.SessionInfo

	Agent interface {
		// 健康检查
		Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
		// 发送用户消息，返回 Agent 回复
		SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error)
		// 获取会话列表
		GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*GetSessionListResponse, error)
		// 获取会话消息历史
		GetMessageHistory(ctx context.Context, in *GetMessageHistoryRequest, opts ...grpc.CallOption) (*GetMessageHistoryResponse, error)
	}

	defaultAgent struct {
		cli zrpc.Client
	}
)

func NewAgent(cli zrpc.Client) Agent {
	return &defaultAgent{
		cli: cli,
	}
}

// 健康检查
func (m *defaultAgent) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

// 发送用户消息，返回 Agent 回复
func (m *defaultAgent) SendMessage(ctx context.Context, in *SendMessageRequest, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.SendMessage(ctx, in, opts...)
}

// 获取会话列表
func (m *defaultAgent) GetSessionList(ctx context.Context, in *GetSessionListRequest, opts ...grpc.CallOption) (*GetSessionListResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.GetSessionList(ctx, in, opts...)
}

// 获取会话消息历史
func (m *defaultAgent) GetMessageHistory(ctx context.Context, in *GetMessageHistoryRequest, opts ...grpc.CallOption) (*GetMessageHistoryResponse, error) {
	client := agent.NewAgentClient(m.cli.Conn())
	return client.GetMessageHistory(ctx, in, opts...)
}
