// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userclient

import (
	"context"

	"SLGaming/back/services/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ChangePasswordRequest             = user.ChangePasswordRequest
	ChangePasswordResponse            = user.ChangePasswordResponse
	ChangePhoneRequest                = user.ChangePhoneRequest
	ChangePhoneResponse               = user.ChangePhoneResponse
	CheckFollowStatusRequest          = user.CheckFollowStatusRequest
	CheckFollowStatusResponse         = user.CheckFollowStatusResponse
	CompanionInfo                     = user.CompanionInfo
	CompanionRankingItem              = user.CompanionRankingItem
	ConsumeRequest                    = user.ConsumeRequest
	ConsumeResponse                   = user.ConsumeResponse
	CreateGameSkillRequest            = user.CreateGameSkillRequest
	CreateGameSkillResponse           = user.CreateGameSkillResponse
	CreateRechargeOrderRequest        = user.CreateRechargeOrderRequest
	CreateRechargeOrderResponse       = user.CreateRechargeOrderResponse
	DeleteGameSkillRequest            = user.DeleteGameSkillRequest
	DeleteGameSkillResponse           = user.DeleteGameSkillResponse
	FollowUserRequest                 = user.FollowUserRequest
	FollowUserResponse                = user.FollowUserResponse
	ForgetPasswordRequest             = user.ForgetPasswordRequest
	ForgetPasswordResponse            = user.ForgetPasswordResponse
	GameSkill                         = user.GameSkill
	GetCompanionListRequest           = user.GetCompanionListRequest
	GetCompanionListResponse          = user.GetCompanionListResponse
	GetCompanionOrdersRankingRequest  = user.GetCompanionOrdersRankingRequest
	GetCompanionOrdersRankingResponse = user.GetCompanionOrdersRankingResponse
	GetCompanionProfileRequest        = user.GetCompanionProfileRequest
	GetCompanionProfileResponse       = user.GetCompanionProfileResponse
	GetCompanionRatingRankingRequest  = user.GetCompanionRatingRankingRequest
	GetCompanionRatingRankingResponse = user.GetCompanionRatingRankingResponse
	GetMutualFollowListRequest        = user.GetMutualFollowListRequest
	GetMutualFollowListResponse       = user.GetMutualFollowListResponse
	GetMyFollowersListRequest         = user.GetMyFollowersListRequest
	GetMyFollowersListResponse        = user.GetMyFollowersListResponse
	GetMyFollowingListRequest         = user.GetMyFollowingListRequest
	GetMyFollowingListResponse        = user.GetMyFollowingListResponse
	GetUserRequest                    = user.GetUserRequest
	GetUserResponse                   = user.GetUserResponse
	GetWalletRequest                  = user.GetWalletRequest
	GetWalletResponse                 = user.GetWalletResponse
	ListGameSkillsRequest             = user.ListGameSkillsRequest
	ListGameSkillsResponse            = user.ListGameSkillsResponse
	LoginByCodeRequest                = user.LoginByCodeRequest
	LoginByCodeResponse               = user.LoginByCodeResponse
	LoginRequest                      = user.LoginRequest
	LoginResponse                     = user.LoginResponse
	RechargeListRequest               = user.RechargeListRequest
	RechargeListResponse              = user.RechargeListResponse
	RechargeOrderInfo                 = user.RechargeOrderInfo
	RechargeRequest                   = user.RechargeRequest
	RechargeResponse                  = user.RechargeResponse
	RegisterRequest                   = user.RegisterRequest
	RegisterResponse                  = user.RegisterResponse
	UnfollowUserRequest               = user.UnfollowUserRequest
	UnfollowUserResponse              = user.UnfollowUserResponse
	UpdateCompanionProfileRequest     = user.UpdateCompanionProfileRequest
	UpdateCompanionProfileResponse    = user.UpdateCompanionProfileResponse
	UpdateCompanionStatsRequest       = user.UpdateCompanionStatsRequest
	UpdateCompanionStatsResponse      = user.UpdateCompanionStatsResponse
	UpdateGameSkillRequest            = user.UpdateGameSkillRequest
	UpdateGameSkillResponse           = user.UpdateGameSkillResponse
	UpdateRechargeOrderStatusRequest  = user.UpdateRechargeOrderStatusRequest
	UpdateRechargeOrderStatusResponse = user.UpdateRechargeOrderStatusResponse
	UpdateUserRequest                 = user.UpdateUserRequest
	UpdateUserResponse                = user.UpdateUserResponse
	UserFollowInfo                    = user.UserFollowInfo
	UserInfo                          = user.UserInfo
	WalletInfo                        = user.WalletInfo

	User interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
		LoginByCode(ctx context.Context, in *LoginByCodeRequest, opts ...grpc.CallOption) (*LoginByCodeResponse, error)
		ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordResponse, error)
		ChangePhone(ctx context.Context, in *ChangePhoneRequest, opts ...grpc.CallOption) (*ChangePhoneResponse, error)
		ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
		// 帅币钱包相关接口
		GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
		Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeResponse, error)
		Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error)
		CreateRechargeOrder(ctx context.Context, in *CreateRechargeOrderRequest, opts ...grpc.CallOption) (*CreateRechargeOrderResponse, error)
		UpdateRechargeOrderStatus(ctx context.Context, in *UpdateRechargeOrderStatusRequest, opts ...grpc.CallOption) (*UpdateRechargeOrderStatusResponse, error)
		RechargeList(ctx context.Context, in *RechargeListRequest, opts ...grpc.CallOption) (*RechargeListResponse, error)
		// 陪玩信息相关接口
		GetCompanionProfile(ctx context.Context, in *GetCompanionProfileRequest, opts ...grpc.CallOption) (*GetCompanionProfileResponse, error)
		UpdateCompanionProfile(ctx context.Context, in *UpdateCompanionProfileRequest, opts ...grpc.CallOption) (*UpdateCompanionProfileResponse, error)
		UpdateCompanionStats(ctx context.Context, in *UpdateCompanionStatsRequest, opts ...grpc.CallOption) (*UpdateCompanionStatsResponse, error)
		GetCompanionList(ctx context.Context, in *GetCompanionListRequest, opts ...grpc.CallOption) (*GetCompanionListResponse, error)
		// 陪玩排名相关接口
		GetCompanionRatingRanking(ctx context.Context, in *GetCompanionRatingRankingRequest, opts ...grpc.CallOption) (*GetCompanionRatingRankingResponse, error)
		GetCompanionOrdersRanking(ctx context.Context, in *GetCompanionOrdersRankingRequest, opts ...grpc.CallOption) (*GetCompanionOrdersRankingResponse, error)
		// 游戏技能管理接口
		ListGameSkills(ctx context.Context, in *ListGameSkillsRequest, opts ...grpc.CallOption) (*ListGameSkillsResponse, error)
		CreateGameSkill(ctx context.Context, in *CreateGameSkillRequest, opts ...grpc.CallOption) (*CreateGameSkillResponse, error)
		UpdateGameSkill(ctx context.Context, in *UpdateGameSkillRequest, opts ...grpc.CallOption) (*UpdateGameSkillResponse, error)
		DeleteGameSkill(ctx context.Context, in *DeleteGameSkillRequest, opts ...grpc.CallOption) (*DeleteGameSkillResponse, error)
		// 关注相关接口
		FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error)
		UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error)
		GetMyFollowingList(ctx context.Context, in *GetMyFollowingListRequest, opts ...grpc.CallOption) (*GetMyFollowingListResponse, error)
		GetMyFollowersList(ctx context.Context, in *GetMyFollowersListRequest, opts ...grpc.CallOption) (*GetMyFollowersListResponse, error)
		GetMutualFollowList(ctx context.Context, in *GetMutualFollowListRequest, opts ...grpc.CallOption) (*GetMutualFollowListResponse, error)
		CheckFollowStatus(ctx context.Context, in *CheckFollowStatusRequest, opts ...grpc.CallOption) (*CheckFollowStatusResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUser) LoginByCode(ctx context.Context, in *LoginByCodeRequest, opts ...grpc.CallOption) (*LoginByCodeResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.LoginByCode(ctx, in, opts...)
}

func (m *defaultUser) ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ForgetPassword(ctx, in, opts...)
}

func (m *defaultUser) ChangePhone(ctx context.Context, in *ChangePhoneRequest, opts ...grpc.CallOption) (*ChangePhoneResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ChangePhone(ctx, in, opts...)
}

func (m *defaultUser) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ChangePassword(ctx, in, opts...)
}

// 帅币钱包相关接口
func (m *defaultUser) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetWallet(ctx, in, opts...)
}

func (m *defaultUser) Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Recharge(ctx, in, opts...)
}

func (m *defaultUser) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Consume(ctx, in, opts...)
}

func (m *defaultUser) CreateRechargeOrder(ctx context.Context, in *CreateRechargeOrderRequest, opts ...grpc.CallOption) (*CreateRechargeOrderResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateRechargeOrder(ctx, in, opts...)
}

func (m *defaultUser) UpdateRechargeOrderStatus(ctx context.Context, in *UpdateRechargeOrderStatusRequest, opts ...grpc.CallOption) (*UpdateRechargeOrderStatusResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateRechargeOrderStatus(ctx, in, opts...)
}

func (m *defaultUser) RechargeList(ctx context.Context, in *RechargeListRequest, opts ...grpc.CallOption) (*RechargeListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.RechargeList(ctx, in, opts...)
}

// 陪玩信息相关接口
func (m *defaultUser) GetCompanionProfile(ctx context.Context, in *GetCompanionProfileRequest, opts ...grpc.CallOption) (*GetCompanionProfileResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetCompanionProfile(ctx, in, opts...)
}

func (m *defaultUser) UpdateCompanionProfile(ctx context.Context, in *UpdateCompanionProfileRequest, opts ...grpc.CallOption) (*UpdateCompanionProfileResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateCompanionProfile(ctx, in, opts...)
}

func (m *defaultUser) UpdateCompanionStats(ctx context.Context, in *UpdateCompanionStatsRequest, opts ...grpc.CallOption) (*UpdateCompanionStatsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateCompanionStats(ctx, in, opts...)
}

func (m *defaultUser) GetCompanionList(ctx context.Context, in *GetCompanionListRequest, opts ...grpc.CallOption) (*GetCompanionListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetCompanionList(ctx, in, opts...)
}

// 陪玩排名相关接口
func (m *defaultUser) GetCompanionRatingRanking(ctx context.Context, in *GetCompanionRatingRankingRequest, opts ...grpc.CallOption) (*GetCompanionRatingRankingResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetCompanionRatingRanking(ctx, in, opts...)
}

func (m *defaultUser) GetCompanionOrdersRanking(ctx context.Context, in *GetCompanionOrdersRankingRequest, opts ...grpc.CallOption) (*GetCompanionOrdersRankingResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetCompanionOrdersRanking(ctx, in, opts...)
}

// 游戏技能管理接口
func (m *defaultUser) ListGameSkills(ctx context.Context, in *ListGameSkillsRequest, opts ...grpc.CallOption) (*ListGameSkillsResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ListGameSkills(ctx, in, opts...)
}

func (m *defaultUser) CreateGameSkill(ctx context.Context, in *CreateGameSkillRequest, opts ...grpc.CallOption) (*CreateGameSkillResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CreateGameSkill(ctx, in, opts...)
}

func (m *defaultUser) UpdateGameSkill(ctx context.Context, in *UpdateGameSkillRequest, opts ...grpc.CallOption) (*UpdateGameSkillResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateGameSkill(ctx, in, opts...)
}

func (m *defaultUser) DeleteGameSkill(ctx context.Context, in *DeleteGameSkillRequest, opts ...grpc.CallOption) (*DeleteGameSkillResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.DeleteGameSkill(ctx, in, opts...)
}

// 关注相关接口
func (m *defaultUser) FollowUser(ctx context.Context, in *FollowUserRequest, opts ...grpc.CallOption) (*FollowUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.FollowUser(ctx, in, opts...)
}

func (m *defaultUser) UnfollowUser(ctx context.Context, in *UnfollowUserRequest, opts ...grpc.CallOption) (*UnfollowUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UnfollowUser(ctx, in, opts...)
}

func (m *defaultUser) GetMyFollowingList(ctx context.Context, in *GetMyFollowingListRequest, opts ...grpc.CallOption) (*GetMyFollowingListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetMyFollowingList(ctx, in, opts...)
}

func (m *defaultUser) GetMyFollowersList(ctx context.Context, in *GetMyFollowersListRequest, opts ...grpc.CallOption) (*GetMyFollowersListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetMyFollowersList(ctx, in, opts...)
}

func (m *defaultUser) GetMutualFollowList(ctx context.Context, in *GetMutualFollowListRequest, opts ...grpc.CallOption) (*GetMutualFollowListResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetMutualFollowList(ctx, in, opts...)
}

func (m *defaultUser) CheckFollowStatus(ctx context.Context, in *CheckFollowStatusRequest, opts ...grpc.CallOption) (*CheckFollowStatusResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.CheckFollowStatus(ctx, in, opts...)
}
