// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userclient

import (
	"context"

	"SLGaming/back/services/user/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ConsumeRequest         = user.ConsumeRequest
	ConsumeResponse        = user.ConsumeResponse
	ForgetPasswordRequest  = user.ForgetPasswordRequest
	ForgetPasswordResponse = user.ForgetPasswordResponse
	GetUserRequest         = user.GetUserRequest
	GetUserResponse        = user.GetUserResponse
	GetWalletRequest       = user.GetWalletRequest
	GetWalletResponse      = user.GetWalletResponse
	LoginByCodeRequest     = user.LoginByCodeRequest
	LoginByCodeResponse    = user.LoginByCodeResponse
	LoginRequest           = user.LoginRequest
	LoginResponse          = user.LoginResponse
	RechargeRequest        = user.RechargeRequest
	RechargeResponse       = user.RechargeResponse
	RegisterRequest        = user.RegisterRequest
	RegisterResponse       = user.RegisterResponse
	UpdateUserRequest      = user.UpdateUserRequest
	UpdateUserResponse     = user.UpdateUserResponse
	UserInfo               = user.UserInfo
	WalletInfo             = user.WalletInfo

	User interface {
		Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
		Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
		GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
		UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
		LoginByCode(ctx context.Context, in *LoginByCodeRequest, opts ...grpc.CallOption) (*LoginByCodeResponse, error)
		ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordResponse, error)
		// 帅币钱包相关接口
		GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error)
		Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeResponse, error)
		Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUser) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}

func (m *defaultUser) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUser) LoginByCode(ctx context.Context, in *LoginByCodeRequest, opts ...grpc.CallOption) (*LoginByCodeResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.LoginByCode(ctx, in, opts...)
}

func (m *defaultUser) ForgetPassword(ctx context.Context, in *ForgetPasswordRequest, opts ...grpc.CallOption) (*ForgetPasswordResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.ForgetPassword(ctx, in, opts...)
}

// 帅币钱包相关接口
func (m *defaultUser) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*GetWalletResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetWallet(ctx, in, opts...)
}

func (m *defaultUser) Recharge(ctx context.Context, in *RechargeRequest, opts ...grpc.CallOption) (*RechargeResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Recharge(ctx, in, opts...)
}

func (m *defaultUser) Consume(ctx context.Context, in *ConsumeRequest, opts ...grpc.CallOption) (*ConsumeResponse, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Consume(ctx, in, opts...)
}
