// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: code.proto

package codeclient

import (
	"context"

	"SLGaming/back/services/code/code"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	SendCodeRequest    = code.SendCodeRequest
	SendCodeResponse   = code.SendCodeResponse
	VerifyCodeRequest  = code.VerifyCodeRequest
	VerifyCodeResponse = code.VerifyCodeResponse

	Code interface {
		SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error)
		VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error)
	}

	defaultCode struct {
		cli zrpc.Client
	}
)

func NewCode(cli zrpc.Client) Code {
	return &defaultCode{
		cli: cli,
	}
}

func (m *defaultCode) SendCode(ctx context.Context, in *SendCodeRequest, opts ...grpc.CallOption) (*SendCodeResponse, error) {
	client := code.NewCodeClient(m.cli.Conn())
	return client.SendCode(ctx, in, opts...)
}

func (m *defaultCode) VerifyCode(ctx context.Context, in *VerifyCodeRequest, opts ...grpc.CallOption) (*VerifyCodeResponse, error) {
	client := code.NewCodeClient(m.cli.Conn())
	return client.VerifyCode(ctx, in, opts...)
}
