// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	code "SLGaming/back/services/gateway/internal/handler/code"
	order "SLGaming/back/services/gateway/internal/handler/order"
	user "SLGaming/back/services/gateway/internal/handler/user"
	"SLGaming/back/services/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/code/send",
				Handler: code.SendCodeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/order",
				Handler: order.CreateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/order",
				Handler: order.GetOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/accept",
				Handler: order.AcceptOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/cancel",
				Handler: order.CancelOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/complete",
				Handler: order.CompleteOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/rate",
				Handler: order.RateOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/order/start",
				Handler: order.StartOrderHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/orders",
				Handler: order.GetOrderListHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/avatar",
				Handler: user.UploadAvatarHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/change-password",
				Handler: user.ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/change-phone",
				Handler: user.ChangePhoneHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/companion/apply",
				Handler: user.ApplyCompanionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/companion/profile",
				Handler: user.GetCompanionProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/companion/profile",
				Handler: user.UpdateCompanionProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/companion/profile/public",
				Handler: user.GetCompanionProfileByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/companion/status",
				Handler: user.UpdateCompanionStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/companions",
				Handler: user.GetCompanionListHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/forgetPassword",
				Handler: user.ForgetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/gameskills",
				Handler: user.ListGameSkillsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login-by-code",
				Handler: user.LoginByCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/logout",
				Handler: user.LogoutHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/recharge",
				Handler: user.RechargeCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/recharge",
				Handler: user.RechargeQueryHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/recharge/alipay/notify",
				Handler: user.AlipayNotifyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/refresh-token",
				Handler: user.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/user/wallet",
				Handler: user.GetWalletHandler(serverCtx),
			},
		},
	)
}
