// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	user "SLGaming/back/services/gateway/internal/handler/user"
	"SLGaming/back/services/gateway/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/user/forgetPassword",
				Handler: user.ForgetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login-by-code",
				Handler: user.LoginByCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
	)
}
